### ISSUE TITLE
Does DML support resume transfer after any exception or just operation cancelled exception?

### ISSUE THREAD

**Issue by hilbert-tan** [Azure/azure-storage-net-data-movement#101]
I have a use case where transfer may fail halfway due to some transient errors, like gateway timeout, then i will catch that exception and resume operation just like described in "Resume a canceled transfer" section of https://docs.microsoft.com/en-us/azure/storage/common/storage-use-data-movement-library . So instead of cancellation exception, it is some other exceptions. 

But when I resume the operation, it started from the last checkpoint, but cannot terminate even after transfer reached the full size of the transfer. 

Is the resume feature tied to operation cancellation exception only or generic to any exception?

**Comment by EmmaZhu** [comment]
It's designed to resume from all kinds of exceptions. Could you share the code to invoke DataMovement library if it's OK?

**Comment by vinjiang** [comment]
Feel free to let us know if  you need further assistance.
