### ISSUE TITLE
Does the TransferManager support concurrency?

### ISSUE THREAD

**Issue by dgodwin1175** [Azure/azure-storage-net-data-movement#102]
Can you confirm that UploadDirectoryAsync will upload the files in the directory in parallel, or are they done sequentially?

Is it possible to have a non-static instance of the TransferManager so I can upload files in parallel?
Rather than calling UploadDirectoryAsync, I want to be able to call UploadAsync on multiple files concurrently (in separate threads), each with it's own SasURL.

**Comment by EmmaZhu** [comment]
DataMovement library transfers data in parallel, in files and in chunks for each file.  UploadAsync will create an async task to do transfer, and DataMovement will schedule each task in parallel. DataMovement library is designed to use as much network resource as possible, we'd suggest using one TransferManager instance on one machine.

**Comment by dgodwin1175** [comment]
Thanks for the reply.
If I have to upload files individually using UploadAsync (as I can only obtain SAS URLs per file), what is the most efficient way to do this?  
Currently I have ServicePointManager configured like so:
ServicePointManager.DefaultConnectionLimit = Environment.ProcessorCount*8;
ServicePointManager.Expect100Continue = false;

What is best practise to get the best performance out of the TransferManager?
Thanks.

**Comment by blueww** [comment]
You can create one UploadAsync() job for each file, and TransferManager can run them in parallel.

**Comment by EmmaZhu** [comment]
The ServicePointManager setting you are using is great. To get best performance, you can set parallel level in TransferManager.Configurations.ParallelOperations according to your network condition.

**Comment by EmmaZhu** [comment]
The ServicePointManager setting you are using is great. To get best performance, you can tune parallel level in TransferManager.Configurations.ParallelOperations according to your network condition.

**Comment by dgodwin1175** [comment]
@blueww I have tried this by making multiple calls to UploadAsync for each file on a separate thread, however I achieved only about the same performance as running it sequentially.
In my example, I sent 64 256MB files in parallel, and all files completed in ~2.5 hours.

@EmmaZhu can you confirm what the default setting is for ParallelOperations and what might be a reasonable setting to use?

**Comment by EmmaZhu** [comment]
You don't need to invoke UploadAsync in separate thread, UploadAsync returns an async task and uploads data in separate threads.

By default, ParallelOperations is 8 * core number which is good for Azure VM, because different sizes of VMs have different network through put. But if you'd want to use DataMovement library in different network environment, you may need to adjust the value accordingly.

**Comment by dgodwin1175** [comment]
I see.  So the idea would be to run all tasks in parallel without waiting and then do a Task.WhenAll() to wait for them all to finish?  I'm wondering how to handle exceptions in this scenario, I assume progress tracking and cancellation is the same?  Do you have any sample code for such a scenario that you could share?
Thanks.

**Comment by dgodwin1175** [comment]
@EmmaZhu my current implementation which uploads files one at a time, supports progress reporting using a ProgressHandler and pause/resume using a TransferCheckpoint on the TransferContext object.
Can I still support this functionality?
Again, some example code of how to use these features when doing parallel uploads would be very useful.
Thanks.

**Comment by dgodwin1175** [comment]
Note that I am still not getting any better performance when I upload multiple files in parallel.  As a test I am no long waiting for the uploadasync, instead I am sending all files asynchronously, and then doing a Task.WhenAll(tasklist) to wait for all of the file upload tasks to complete.

I find, as in my original post, the time to upload 64 256MB files is still taking about 2.5 hours, which is the same as it takes when I upload each file synchronously.

Any thoughts on how I can improve this upload time?
Thanks.

**Comment by EmmaZhu** [comment]
@dgodwin1175  You can find sample to upload blob here: 
https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L96

There are several event handlers in `SingleTransferContext` which you can use to get each item's transfer status.
For example, you can implement an event handler of `public event EventHandler<TransferEventArgs> FileFailed;` to get detailed exception of failed items.

I just try with uploading 16 * 256MB block blobs in our corpnet to azure storage. It takes about 6 mins. The code is very simple, it just adds Task instance returned by `TransferManager.UploadAsync` into a List and Task.WaitAll on all tasks in the List. 

The speed could also be limited by network between your machine and azure storage.  If network bandwidth between your machine and azure storage is not high enough, it might be faster with a lower parallel level to avoid too much pressure on network.

Thanks
Emma

**Comment by blueww** [comment]
@dgodwin1175

We will close this issue now since not hear from you from a long time.
Feel free to reopen it if you have futher questions on this.
