### ISSUE TITLE
 Transient Error on DML DownloadDirectoryAsync with None Error Code

### ISSUE THREAD

**Issue by hilbert-tan** [Azure/azure-storage-net-data-movement#111]
I just onboarded on using DML to do azure blob container transfer. Most of the time DML is working great, but occasionally we saw transient errors during DownloadDirectoryAsync with no clear error information.

The error thrown by DML was :

DownloadDirectoryAsync failed with 1 files failed and 0 files skipped. };Microsoft.WindowsAzure.Storage.DataMovement.TransferException
Message: DownloadDirectoryAsync failed with 1 files failed and 0 files skipped.

And I tried to print out TransferErrorCode which was not included in the TransferException Message above, and it returned: DML throws transfer exception with error code None. Both these messages and error code does not give any indication on what happened during the transfer.

I have some runner tests trying to verify this, since the runner tests are having the same blob structure in container, I suppose the error was not caused by unusual file directory structure/hierarchy. So why is it happen sometime and not the other?

Is this an known issue?

**Comment by EmmaZhu** [comment]
@hilbert-tan `DownloadDirectoryAsync` is supposed to download multiple files in a directory. For there could be very large count of blobs in the source directory, we cannot hold all exceptions in memory to throw out at the very end. Instead, we choose to report error on each individual blob with `FileFailed` in `DirectoryTransferContext`. Could you try with `FileFailed` and give us the error you got?

**Comment by vinjiang** [comment]
Please let us know if you need further assistance. Thanks!
