### ISSUE TITLE
StatusMessage:Egress is over the account limit.

### ISSUE THREAD

**Issue by MayankSri** [Azure/azure-storage-net-data-movement#115]
I'm getting the error below trying update high volume of documents to Blob storage using data movement library.

` Request Information`
` RequestID:ea3cca9d-001e-00f1-6dfc-a43410000000`
` RequestDate:Tue, 13 Feb 2018 18:59:30 GMT`
` StatusMessage:Egress is over the account limit.`
` ErrorCode:ServerBusy`
` ErrorMessage:Egress is over the account limit. RequestId:ea3cca9d-001e-00f1-6dfc-a43410000000 ``Time:2018-02-13T18:59:30.9701127Z`
` The remote server returned an error: (503) Server Unavailable.`

My understanding is the data movement library makes multiple parallel connections to read write blobs.
Does each such parallel connection count against the Max requests per second limit?

**Comment by jiacfan** [comment]
Hi, @MayankSri 

The parallel connection count is 8 * ProcessorCount by default, and would not be adjuested or calculated according to Service side SLA currently. Please refer to [scalability targets for Azure storage account](https://docs.microsoft.com/en-us/azure/storage/common/storage-scalability-targets#scalability-targets-for-a-storage-account) for more details about Blob service's SLA for egress.

The error code and error message you pasted shows a typical throttling case which Egress limitation is exceeded. DMLib would retry on such errors by default, and to mitigate such errors please try to set the parallel count explicitly to less (e.g. 4 * ProcessorCount) which meets your storage account's SLA.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
@MayankSri 

Please let us know if you need further assist.

Best Wishes,
Jiachen
