### ISSUE TITLE
Upload/DownloadDirectoryAsync with GUI

### ISSUE THREAD

**Issue by wbirsak** [Azure/azure-storage-net-data-movement#116]
Hi,

I am currently checking out the samples of the datamovement. Especially the samples about how to upload/down a complete folder to Azure Blob storage.

These are all console application and are workig, but i am trying to create a gui application for this.

Uploading part is working, progresshandler updates a progressbar.
when I am try to do the download, it doesn't download, it moves to the progresshandles but then nothing happens. The folder on the local drive is created.. but no files are downloaded.

Upload Code:
        public static void UploadToCloud(DataMove dm)
        {
            TransferCheckpoint checkpoint = null;
            DirectoryTransferContext context = GetDirectoryTransferContext(checkpoint, dm);
            UploadDirectoryOptions options = GetUploadDirectoryOptions();
            dm.CancellationTokenSource = new CancellationTokenSource();
            Task task;
            try
            {
                dm.LogMessage(string.Format("Upload started of {0} zips.", dm.ExpectedFiles));
                dm.StartTimer();
                task = TransferManager.UploadDirectoryAsync(dm.LocalFolder, dm.BlobDirectory, options, context, dm.CancellationTokenSource.Token);
            }
            catch (Exception e)
            {
                dm.LogMessage(e.Message);
            }
        }
		
Download Code:
        public static void DownloadFromCloud(DataMove dm)
        {
            TransferCheckpoint checkpoint = null;
            DirectoryTransferContext context = GetDirectoryTransferContext(checkpoint, dm);
            DownloadDirectoryOptions options = GetDownloadDirectoryOptions();
            dm.CancellationTokenSource = new CancellationTokenSource();
            Task task;
            try
            {
                dm.LogMessage(string.Format("Download started of {0} zips.", dm.ExpectedFiles));
                dm.StartTimer();
                task = TransferManager.DownloadDirectoryAsync(dm.BlobDirectory, dm.LocalFolder, options, context, dm.CancellationTokenSource.Token);
            }
            catch (Exception e)
            {
                dm.LogMessage(e.Message);
            }
        }

I am new to this (C#) and maybe i am doing this wrong. some help is appreciated, if you need to see more code, let me know.

What I am trying to make is: upload/download tool for an entire directory, a gui for parameters input, that remains responsive and shows progress.

Thanks in advance,
Wesley

**Comment by jiacfan** [comment]
Hi, @wbirsak 

Would you share the error messages for the case "no files are transferred, while progress is updated normally"?

Thanks,
Jiachen

**Comment by wbirsak** [comment]
Hi Jiachen,

There are no error message when I running it in debug, I am afraid. It passes thru the progresshandler a couple of times, all the parameters have the  0 value.. then it's done. I exactly doing the opposite for uploading a local directory and that works fine.  When I do this in the console application, it does download the files in the container to the local folder.

The main difference is that I don't call the await / wait() in the methods in gui application.

**Comment by jiacfan** [comment]
@wbirsak 

For DMLib, it'll be great if there is any error message, which can help us to do the investigation. In this particular case, please debug the transfer thread's life cycle, it's possible that the thread use for transfer is forced to be finished before the transfer get finished.

Best Wishes,
Jiachen

**Comment by jiacfan** [comment]
@wbirsak 
If you need further assist, please let us know.

Best Wishes,
jiachen

**Comment by wbirsak** [comment]
Hi, sorry for my late response! I was a bit busy.
The problem was in the download directory options, when I added:
options.SearchPatter = "*.zip" 
is seems to be waiting.. when I leave this property at default it works.

**Comment by vinjiang** [comment]
It seems the searching against Azure Storage. What's the scope of searching, tens of objects or thousands? You may tell if the application is just running on background or hung by checking network trace. Usually, when doing searching, it will list the destination, BTW, for search pattern, 'When source is Azure blob directory, if recursive is set to true, SearchPattern is matched against source blob as name **prefix**. Otherwise, only Azure blob with the exact name specified by SearchPattern will be matched', you can find more details about SearchPattern usage here:

https://azure.github.io/azure-storage-net-data-movement/html/4d8115ba-2ee4-ff85-1ee4-ada777cf6284.htm
