### ISSUE TITLE
BlobDownload Progress callback is not called and download hangs

### ISSUE THREAD

**Issue by KiranBabu-Kirando** [Azure/azure-storage-net-data-movement#120]
We frequently see that blob download and upload hangs indefinitely and no Progress callback is called. This can be seen for any file size. I have given below a sample of blobdownload we have seen recently. This is affecting our SLA's and customer impact.

DML version used 0.7.0 

Case1: 
Blob got downloaded but the progress callback was not called and hence the download was in hanging state. Why is progress callback not called ?
FileSize is 914019 bytes

Case2:
Blob Got downloaded at 9:23:04 AM and the code invoking dml blobdownload got response back that download is completed at 9:49:09 AM. Progress callback was called in this case. Why the time lag ?
FileSize is 914197 bytes

**Comment by jiacfan** [comment]
Hi, @KiranBabu-Kirando 

As your description, did the issue happen only for blob downloading? What's the type of blob, only block blob or even append/page blob can repo the issue? What kind of API you are using, could you provide a example(is it single file transfer or directory transfer) and params?

For Case 1: Does "Blob got downloaded" mean you have seen a local file created, and validated the data of it is with same MD5 as blob saved in Azure storage service? For progress callback not called, could you further confirm for example when FileSize is 914019 bytes, what's the `BytesTransferred` in `TransferStatus` of the last reported progress? And could you provide a dump file for the hang case?

For Case 2: Please provide the progress log of `BytesTransferred` in `TransferStatus`, and we can further investigate if there is some network issue, which could cause some of blocks fail to be downloaded and potentially causing the hang.

Thanks,
Jiachen

**Comment by KiranBabu-Kirando** [comment]
Most of cases happen on BlobDownload. Its a Block Blob. Its is a single filetransfer using SyncTransferController. The params are straight forward. Input in blob sas uri and destination is local path on the disk and sometimes remote path, DownloadOptions.DisableContentMD5Validation is false, SharedTransferContext.ShouldOverwriteCallback  return true.

Case 1 : I did not validate hash. The test I am doing I am generating file on the fly and then validating hash at the end of the transfer. because of the hang I am not able to validate hash. For every progress call back I log the same details to my telemetry and I do not see any telemetry which means progress call back was not called.

Case 2 : The blob got downloaded 100% percent. But the code invoking dml blob download got response back after 26 minutes.

I am not able to attach the Dump file it is exceeding the 10 MB size limit. Provide me a share and I can copy them there.

**Comment by jiacfan** [comment]
Hi, @KiranBabu-Kirando 

For Case 1:
Does
"For every progress call back I log the same details to my telemetry and I do not see any telemetry which means progress call back was **not** called."
want to express, progress callback is never called?

Please email jiacfan@microsoft.com, we'll provide a temporary share for dump file, it would be great if you can provide dump for both Case 1 and Case 2.

Thanks,
Jiachen

**Comment by KiranBabu-Kirando** [comment]
Yes for Case 1 Progress callback was never called. I will email with the dump files.

**Comment by jiacfan** [comment]
@KiranBabu-Kirando 

Thanks! Checking.

**Comment by jiacfan** [comment]
Hey, @KiranBabu-Kirando 

Is there still problem on this question, or it can be closed?

Thanks,
Jiachen
