### ISSUE TITLE
azcopy 7.1.0-netcorepreview 0 is failing to upload folder in linux machine

### ISSUE THREAD

**Issue by KiranKumarUmmarasetty** [Azure/azure-storage-net-data-movement#121]
Hey there, I hope this is the right place for my issue.
We have been trying to upload a folder and it failing to upload for the first time. If we are executing the command in the command prompt at the second time it is working...
The following is the command.
Kindly help me on this..

sudo azcopy --quiet --source /home/pftadmin/AzureDemo/TempAzure/5028-26287/ingestutil/others --destination https://<mydomain>/content/nmdcAzureDemo/20180412/others/ --resume /home/pftadmin/journal/5028--29835--133451 --dest-key <mykey> --recursive 

/home/pftadmin/AzureDemo/TempAzure/5028-26287/ingestutil/others/36202.jpg: Failed to open file /home/pftadmin/AzureDemo/TempAzure/5028-26287/ingestutil/others/36202.jpg: Invalid argument.

**Comment by EmmaZhu** [comment]
@KiranKumarUmmarasetty  
Were you using exactly the same command line to start the two processes? Can this issue be reproduced or it just happened once? 

And could you also share the whole output from AzCopy? I think there should a transfer summary to indicate to indicate total transfer count, failed count, etc. 

Thanks
Emma

**Comment by EmmaZhu** [comment]
@KiranKumarUmmarasetty 
I'll close this issue for now, if you need any further help, please feel free to reopen it or open a new one.
