### ISSUE TITLE
Blob Upload sas uri perms

### ISSUE THREAD

**Issue by KiranBabu-Kirando** [Azure/azure-storage-net-data-movement#126]
Hi,
While trying to upload blob that dos not exist, we have observed that the sas uri needs both read and write perms. In general write perms should be good enough for blob that does not exist. Returning true or false for SingleTransferContext().ShouldOverwriteCallback() does not have any effect on the sas uri perms. 
Am I missing something ? If not can this be fixed.

Thanks,
Kiran

**Comment by EmmaZhu** [comment]
Hi Kiran,

Before data transferring, DMLib tries to check destination's existence first. Assigning TransferContext.ForceOverwrite to SingleTransferContext().ShouldOverwriteCallback can force DMLib to skip this check operation, this way it would not require READ permission on destination anymore.

Thanks
Emma

**Comment by EmmaZhu** [comment]
@KiranBabu-Kirando 
I'll close this issue for now, if you need further help, please feel free to reopen it or open a new one.
