### ISSUE TITLE
Exceptions for Blob To Blob Copy

### ISSUE THREAD

**Issue by KiranBabu-Kirando** [Azure/azure-storage-net-data-movement#127]
Hi,
Is there a way to distinguish exceptions generated for source and destination sas uri ? This would help us to execute business logic based on source uri exceptions or destination uri exceptions.

Thanks,
Kiran

**Comment by EmmaZhu** [comment]
Hi Kiran,

I cannot fully understand your scenario. Would you want to do a directory transfer or a single file transfer?

For failures each individual transfer item, we have a event: FileFailed, event argument is defined in TransferEventArgs. You can find corresponding source instance, destination instance and exception in the TransferEventArgs.

Thanks
Emma

**Comment by EmmaZhu** [comment]
@KiranBabu-Kirando  
I'll close this issue for now, if you need any further help, feel free to reopen it or open a new one.
