### ISSUE TITLE
Setting CopyOptions for Incremental Copy

### ISSUE THREAD

**Issue by markjbrown** [Azure/azure-storage-net-data-movement#13]
I'm having some trouble understanding the correct settings for CopyOptions to allow DML to overwrite a file when it exists on the transfer destination location.

I've tried multiple combinations of AccessConditions on the source and destination but getting failures on the transfer.

What is the CopyOptions to allow for an incremental copy where the source is newer than the destination to force an overwrite?

Thanks much.

**Comment by nowenL** [comment]
Hi, Mark

I suppose you are using CopyAsync(CloudBlob sourceBlob, CloudBlob destBlob, bool isServiceCopy, CopyOptions options, TransferContext context). Since you already got sourceBlob & destBlob before calling CopyAsync, you can fetch the attribute of them and decide whether to do the copy or not according to their LastModified properties. 

By default, DML will not overwrite an existing destination, you can force the overwrite by provide a OverwriteCallback in TransferContext. Here's the code snippet for your reference:

            // Fetch blob attributes from server
            sourceBlob.FetchAttributes();
            destBlob.FetchAttributes();

            // Check if the source blob is newer than the destination blob.
            if (sourceBlob.Properties.LastModified > destBlob.Properties.LastModified)
            {
                TransferContext transferContext = new TransferContext()
                {
                    OverwriteCallback = (source, destination) =>
                    {
                        // This callback is triggered when DML find the destination already exists.
                        // Return true to overwrite the destination, false to skip.
                        return true;
                    }
                };

                await TransferManager.CopyAsync(sourceBlob, destBlob, false /* isServiceCopy */, null /* options */, transferContext);
            }

**Comment by markjbrown** [comment]
Interesting. Thanks for this.

So when doing an incremental /XO type of copy then do I even need to use or set CopyOptions? 

It seems to me I could just set the Overwrite delegate to a function and then in my delegate check whether I'm doing an incremental copy in the first place and if I am, then check if the source is newer than the destination by checking the blob properties using the CloudBlob objects hydrated from the URI's passed into the delegate.

Is that correct?

Thanks,
Mark

**Comment by nowenL** [comment]
Correct. CopyOptions provide a way to set conditional header in requests sent to source/destination blobs and it doesn't help in this scenario. 

You can either check whether the source is newer than destination before call DML or inside the Overwrite delegate as you mentioned. A small difference is if you do it inside the Overwrite delegate and returns false to not overwrite the destination. The corresponding Task return by CopyAsync will end up with an exception indicating the copy is skipped.

Best Regards,
Longwen

**Comment by markjbrown** [comment]
I have a question about this.

Can you tell me what the error message is when a copy is skipped within the Overwrite callback?

I am using the callback now to determine whether to copy the file or not. When there are no files skipped there are no errors. When there are files skipped I am getting an exception. However the exception is, "Object reference not set to an instance of an object."

Is that the error I should see?
