### ISSUE TITLE
Unicode symbols are changing during tables export/import?

### ISSUE THREAD

**Issue by DeV1L** [Azure/azure-storage-net-data-movement#130]
I have a table with Unicode symbols.
[![enter image description here][1]][1]

After it exported to JSON (I've tried Table Service REST API and AzCopy) and imported to the new table, symbols are changed.

[![enter image description here][2]][2]

[![enter image description here][3]][3]

How I can avoid it during export/import?

  [1]: https://i.stack.imgur.com/7u3u9.png
  [2]: https://i.stack.imgur.com/KqKoO.png
  [3]: https://i.stack.imgur.com/CwJM9.png

**Comment by jiacfan** [comment]
Hi, @DeV1L 

Thanks for reporting issue, and sorry for the delay. Has the issue been solved?

I see you mentioned you have tried both Table Service REST API and AzCopy, so when you directly use Table Service REST API(or Azure storage .Net client library), can the issue mentioned be repoed?

If it's possible, would you please share the unicode could repo the issue in decimal or hexadecimal format to us? And we'll try to repo the issue locally, and see if it's a bug, or any solution(work around) can be shared,

Thanks,
Jiachen

**Comment by EmmaZhu** [comment]
@DeV1L  No response for quite a long time, will close this issue for now. Please feel free to reopen it or open a new one if any help needed.
