### ISSUE TITLE
Azcopy add support to copy files to $web container

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-storage-net-data-movement#133]
In this new feature--[Static website hosting for Azure Storage now in public preview](https://azure.microsoft.com/en-us/blog/azure-storage-static-web-hosting-public-preview). A container `$web` will be created for hosting static websites. 

The problem is, Azcopy can't recognize this container, test in cmd

`[ERROR] Error parsing destination location "https://{accountname}.blob.core.windows.net/$web": Invalid location 'https://{accountname}.blob.core.windows.net/$web', address could not be parsed.`

Also test in powershell, no breaking, but files are just uploaded to `$root` despite the name after `$`.

For now seems that it can only resolve container `$root`  with `$` in name.

**Comment by onpaws** [comment]
Yesterday I tried to use static website hosting by setting up a release task in VSTS. 
VSTS uses an older version of AzCopy (apparently v2.0.1) and it doesn't support `$web`.
I manually tested on my local machine using a fresher version of AzCopy, but same behavior.

AzCopy v7.1.0, then I tried 8.0.0-netcorepreview - still broken.
Win10 Enterprise build 17704

**Comment by jiacfan** [comment]
Hi, @JohnReeson  and @onpaws:

Sorry that AzCopy v7.1.0 doesn't support static website, and we'll release a new version AzCopy recently which involves static website support, it will be hopefully in this week.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
@rajatagrawal-dev 

The next version would likely be a minor version(7.4.0), there should not be any breaking change. Will update this thread if there is any change.

Best Wishes,
Jiachen

**Comment by onpaws** [comment]
Thanks for the update @jiacfan.
If there's a way I can help test I'd be happy to

**Comment by MrBRUE** [comment]
@jiacfan - will that azcopy update be available on Azure Cloud Shell right away, too? (Will that version there be immediately upgraded?) --tested it on my beloved Cloud Shell and $web broke everything.

**Comment by hoetz** [comment]
FYI until AzCopy supports it you can use the Azure CLI to copy files to the $web container. Worked for me:

`az storage blob upload-batch --account-name myaccount -s . -d $web`

**Comment by jiacfan** [comment]
Hi, @MrBRUE 

Thanks for providing feedback, FYI,  [v7.3.0](https://aka.ms/downloadazcopy) has been released(Windows, based on .Net Framework), involved $web support. The Azure Cloud Shell support hasn't yet get ready, and I have established a tracking item to follow. Will share more details once get any update on the Cloud Shell support.

Thanks,
Jiachen

**Comment by tpetrina** [comment]
@hoetz Where did you test that? On macOS it doesn't work. The error is:
```
az storage blob upload-batch: error: argument --destination/-d: expected one argument
```

**Comment by tpetrina** [comment]
@onpaws Wow, that did the trick! Thanks!

**Comment by vivaladan** [comment]
@jiacfan Thanks for the fix!

@rajatagrawal-dev Any idea when we'll see this available on VSTS hosted agents?

**Comment by rajatagrawal-dev** [comment]
@vivaladan This is a fix in the Azure File Copy v2 task itself and not the agent. Your VSTS account will be updated with the new task version soon. The deployment is scheduled to start by early next week.

**Comment by EmmaZhu** [comment]
As $web has been supported in AzCopy, close this issue, Please feel free to reopen it or open a new issue if any further assistant needed.

**Comment by mikeclymer** [comment]
@rajatagrawal-dev - Has this fix been released to the VSTS Azure File Copy v2 task yet? I am still seeing the issue in my release pipeline.

**Comment by rajatagrawal-dev** [comment]
@mikeclymer Please follow #7611 for updates.

**Comment by 123dev** [comment]
> Thanks for providing feedback, FYI, v7.3.0 has been released(Windows, based on .Net Framework), involved $web support. The Azure Cloud Shell support hasn't yet get ready, and I have established a tracking item to follow. Will share more details once get any update on the Cloud Shell support.

> Thanks,
> Jiachen

Thanks, is there a Linux version available for download?

**Comment by jiacfan** [comment]
@123dev 

Yes, please download AzCopy v7.3.0-netcore from [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-linux?toc=%2fazure%2fstorage%2fblobs%2ftoc.json) 
+ Raw link again:
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-linux?toc=%2fazure%2fstorage%2fblobs%2ftoc.json

The document will be updated accordingly as well.

Thanks,
Jiachen

**Comment by 123dev** [comment]
@jiacfan 
Thanks, and sorry for the delayed response.
Tried installing it on MacOS
can't install into /usr/lib
So I modified the install script to install it to /usr/local
and the binary into /usr/local/bin
however I always get
**-bash: ./azcopy: cannot execute binary file**

I assume it doesn't work on a MAC?

Thanks

**Comment by brgsstm** [comment]
Has this been released into Azure DevOps (VSTS) yet?  I am still seeing issues in the release pipeline trying to copy to $web.

**Comment by jiacfan** [comment]
Hi, @rajatagrawal-dev @brgsstm 

@rajatagrawal-dev  please let us know if this is released into Azure DevOps(VSTS), and please let us know if there is any issue for integration.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
@brgsstm 

Thanks for the info!

**Comment by yentsun** [comment]
Why is this issue closed? 

azcopy 7.3.0-netcore:
```
azcopy --source ./build --destination https://mystorage.blob.core.windows.net/$web --recursive --dest-key <key>
```
Results in bunch of messages like:
```
[2019/02/07 20:01:04][ERROR] /build/static/js/main.bad2dbc9.js: The transfer failed.                                                
The requested URI does not represent any resource on the server.
HttpStatusMessage:The requested URI does not represent any resource on the server.
```
And files uploaded in `$root` container instead of `$web`

**Comment by nikhiltechahead** [comment]
> @tpetrina try putting `\` a backslash in front of `$web` so your shell (likely bash) doesn't try to parse the $

It works correctly. Thanks!
