### ISSUE TITLE
Feature Request: AzCopy support to retry on HTTP 412 precondition failed

### ISSUE THREAD

**Issue by tknerr** [Azure/azure-storage-net-data-movement#135]
Hi everybody, 

not sure if this is the correct place to raise this feature request, but I haven't found a better one yet ;-)

**Goal**: copy all blobs of a specific container from storage account A to storage account B

**Problem**: blobs might be written to while you want to copy them (especially with AppendBlobs which are meant to be appended to by nature). We have quite a lot of such append Blobs which are being written to every minute. Now whenever I start `AzCopy` to async copy the blobs from account A to account B, I get the following errors quite often:

```
Failed to copy from "https://accounta.blob.core.windows.net/foo/<some guid>.csv" to "https://accountb.blob.core.windows.net/foo/<some guid>.csv". Copy status: Failed; Description: 412 ConditionNotMet "Copy failed when reading the source.".
```

I can reproduce this behaviour whenever the contents of the source blob are changing. From a BlobStorage API perspective I suppose this is due to `AzCopy` doing list operation first, and once it comes to retrieving the actual file the content has changed and so does the ETag and that's why we get an HTTP 412 here (just guessing).

Retrying from the journal log does not help here as it fails immediately with an HTTP 412. I believe the journal log still contains the ETag from the original list operation (again just guessing, might be a not-modified-since conditional header too).

I have checked AzCopy commandline parameters but really haven't found any option to retry on HTTP 412. Currently the only workaround I see is wrap everything in a script that parses the stderr of the original AzCopy call (transfer all blobs from A to B) and then retry the failed blobs individually (if any) by spawning yet another individual AzCopy call for each of these.

From an end user perspective, I simply want a command line tool to copy blobs from A to B. 

Is there a simpler solution to that?

**Comment by blueww** [comment]
@tknerr 
Thanks for raise this feature request!
We will investigate it and update you later.

**Comment by tknerr** [comment]
thanks @blueww for double-checking!

**Comment by blueww** [comment]
@tknerr 
Do you mind we close the issue, and the root cause is clear (not support), and won't fix in a recent future.
Let me know if you have any concern. :)

**Comment by tknerr** [comment]
@blueww no worries with closing. Thanks again!
