### ISSUE TITLE
ShouldOverwriteCallbackAsync in TransferContext does not evaluate using the provided delegate.

### ISSUE THREAD

**Issue by yashs-dev** [Azure/azure-storage-net-data-movement#145]
### Which service(blob, file) does this issue concern? 
Blob but should affect others too.
 
### Which version of the SDK was used?
8.0.1

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.Net Core 2.0

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
Use a user provided ShouldOverwriteCallbackAsync in Upload blob transfer context.
 
### What problem was encountered?
ShouldOverwriteCallbackAsync in TransferContext does not evaluate using the provided delegate. It specifically checks whether the callback is TransferContext.ForceOverwrite or not.
        /// <summary>
        /// Gets whether to force overwrite the destination without existence check.
        /// </summary>
        public bool IsForceOverwrite
        {
            get
            {
                if (this.TransferJob.Transfer.Context == null)
                {
                    return false;
                }

                return this.TransferJob.Transfer.Context.ShouldOverwriteCallbackAsync == TransferContext.ForceOverwrite;
            }
        }
 
### Have you found a mitigation/solution?
Yes, I am using the TransferContext.ForceOverwrite but it should really call the user provided delegate.

**Comment by jiacfan** [comment]
Hi, @yashs-dev 

Thanks for reaching us and report the issue.

Would you check if IsForceOverwrite is set to True in your case? `ShouldOverwriteCallbackAsync` will take effect when `IsForceOverwrite` equals to `False`.

E.g. In BlockBlobWriter.cs there is logic:
```
            if (!this.Controller.IsForceOverwrite)
            {
                // If destination file exists, query user whether to overwrite it.
                await this.Controller.CheckOverwriteAsync(
                    existingBlob,
                    this.SharedTransferData.TransferJob.Source.Instance,
                    this.destLocation.Blob);
            }
```

And DMLib has `CheckOverwriteAsync` logic as below:

```
        public async Task CheckOverwriteAsync(
            bool exist,
            object source,
            object dest)
        {
            if (null == this.TransferJob.Overwrite)
            {
                if (exist)
                {
                    if (null == this.TransferContext || null == this.TransferContext.ShouldOverwriteCallbackAsync || !await this.TransferContext.ShouldOverwriteCallbackAsync(source, dest))
                    {
                        this.TransferJob.Overwrite = false;
                    }
                    else
                    {
                        this.TransferJob.Overwrite = true;
                    }
                }
                else
                {
                    this.TransferJob.Overwrite = true;
                }
            }

            this.TransferJob.Transfer.UpdateJournal();

            if (exist && !this.TransferJob.Overwrite.Value)
            {
                string exceptionMessage = string.Format(CultureInfo.InvariantCulture, Resources.OverwriteCallbackCancelTransferException, source.ConvertToString(), dest.ConvertToString());
                throw new TransferSkippedException(exceptionMessage);
            }
        }
```

Thanks,
Jiachen

**Comment by jiacfan** [comment]
Close as no feedback is collected for months.
