### ISSUE TITLE
CopyDirectoryAsync

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-storage-net-data-movement#146]
The CopyDirectoryAsync is not working as expected in AzureFuctions a container gets created, however no data form the source container gets copied ?

**Comment by blueww** [comment]
@grahamehorner 

Could you give more details for this issue, so we can do more investigate on it?
1.  What's the DMlib version, and OS version?
2. Do you wait for the copy task finish? Is there any error/exception reported?
3. How do you call the  CopyDirectoryAsync() function? Could you share your code? (hide credential).

**Comment by blueww** [comment]
@grahamehorner 
Let us know if you still need any support from us?
I will close the issue after several days if not hear from you.
