### ISSUE TITLE
DataMovement based on Microsoft.Azure.Storage.Blob 9.4.0

### ISSUE THREAD

**Issue by prorok-kane** [Azure/azure-storage-net-data-movement#149]
Hi.
DataMovement based on Microsoft.Azure.Storage.Blob 9.4.0
Is it possible in near future?

**Comment by blueww** [comment]
Would you please share your user scenario to use 9.4.0? Why you need DMlib must based on 9.4.0?
Then we can eveluate it according to the this?

**Comment by prorok-kane** [comment]
Now I'm using Microsoft.Azure.Storage.Blob 9.4.0 because of legacy code with sync methods.
Based on this I should reference DataMovement with PrivateAssets.
Otherwise ambiguous reference will happen.
Also I should reference WindowsAzure.Storage 9.3.2 to parent project because "could not load file or assembly" happen in runtime.

**Comment by blueww** [comment]
@EmmaZhu 
Would you please help to look at the request for DMlib based XSCL 9.4.0.

**Comment by blueww** [comment]
@prorok-kane 
Microsoft.Azure.Storage.Blob 9.4.0 is on new framework with new interface, compare to WindowsAzure.Storage lib, which DMlib is currently depend on.

We will discuss that in feature team first, and reply you later.

**Comment by blueww** [comment]
@prorok-kane 
We are now evaluating the effort to migrate to Microsoft.Azure.Storage.Blob 9.4.0. Will update you when get some result.

**Comment by blueww** [comment]
The latest DMlib already based on Microsoft.Azure.Storage.Blob 9.4.2.
So the issue is resolved.
