### ISSUE TITLE
AzCopy v10 + High Volume Copies + Copy Status

### ISSUE THREAD

**Issue by mayoatbm** [Azure/azure-storage-net-data-movement#157]
### Which service(blob, file) does this issue concern? 
Blob
 
### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.Net Core

### Questions 
Hey folks, thanks for all your hard work. 

We have a couple of questions about this library and AzCopy that will help us decide if we need to switch over a high volume use case  to these tools.

- Is there feature parity between the data movement library and AzCopy v10 (preview)? 
- If we use AzCopy to trigger a container/directory copy from one storage account to another, will the job status include details of the individual blobs e.g. if some of the blobs in the container/directory can't be copied for some reason, will we be able to get a list of failed blobs or will we just learn that the job failed. Do we need to issue an AzCopy copy command for each blob individually to get these details?
- Are the data movement library / AzCopy tools the right ones for this use case (see below)?

For context, here's our use case...
We need to copy 8+ million blobs (total 25+ TB) from one storage account to N other storage accounts i.e. distribute the source across the destinations). We would like to know overall progress (total completed, failed,pending etc) but also individual details such as the list of failed blobs and the failure description.

We currently use the async blob copy feature of the storage service. This has some nice properties in that (we don't have to download the blobs, async) but we also don't have a lot of details on progress, failures etc without polling 8 million plus copy ids. 

Would using the Put Block Method From Url work in our case? It looks synchronous and would also take two calls per blob (to complete the block list) vs the async copy. 

Thoughts?

EDIT: Some additional details about how we do this now and one more question.

**Comment by mayoatbm** [comment]
Hey @jiacfan

Thanks for responding so quickly and in such detailed fashion.

Some more context. We're actually running this whole ingestion process in Azure Functions (there are other pieces of work involved like millions of  metadata files to process) so we'd probably prefer .net code over command line (not tied AzCopy v10). 

Some more followup questions/notes:

- We are only using block blobs so we should be able to take advantage of PutBlockFromUrl
- When you say that PutBlockFromUrl is faster than Async Copy. Do you mean individually for a single blob  (e.g. network is faster), or that when moving a large number of blobs, the sync option ends up faster because it does work immediately? Right now each individual Async Copy  call is fast (< 150ms) for our code so we'd like to get a sense of how much longer each call would take if we used PutBlockFromUrl (each blob to copy is 3.175MB). That should tell how much longer our ingestion pipeline will take if we do sync
-  Since we're using Azure Functions (consumption plan) for this ingestion process, our usual pattern is to split up all the work into small pieces and assign a function to do each piece (queue based fan out) versus long running processes on a powerful machine. Do you see any obstacles to this approach with PutBlockFromUrl? We would have potentially hundreds of functions in parallel all calling PutBlockFromUrl to move a single blob over with queue based retries. We would then be able to log failures at an individual level. 

Thoughts?

**Comment by jiacfan** [comment]
Hi, @mayoatbm 

Here is more info about [PutBlockFromUrl](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-from-url) and [CopyBlob](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob), several thing worth mention:

- PutBlockFromUrl is in block level, i.e. after put block, user need call [Put Block List](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list). While copy blob rest API, or the sync(downloadupload)/async(wrapper of copy blob rest api)  I mentioned implemented in this library is in blob level. (Please note which approach might be better suitable for your scenario.)
- FYI, PutBlockFromUrl is available through [Azure storage .Net SDK](https://github.com/azure/azure-storage-net)
- For perf, Copy blob is async, when the blob copy actually happens and finishes depends service side's load, which is different from PutBlockFromUrl is sync fashion.

And personally I think there could be several solutions:
- If your system wish to handle parallel in block level, pls note to call PutBlockList after finishing transferring blocks of blob, and you need your own logic to handle resume, and copy properties.
- If your system wish to handle parallel in blob level, sync(downloadupload) supported in this library could also be considered. It can help you to resume, and copy properties of source to destination.
- If your system wish to handle parallel in blob level, and if binary tool(azcopy-v10) is acceptable, azcopy-v10 worth a try as well, it supports PutBlocList, resume and copy properties.

Best Regards,
Jiachen

**Comment by mayoatbm** [comment]
Hey @jiacfan 

Thanks for the additional info. 

- PutBlockFromUrl seems like a good middle ground for us. As you've mentioned, no client bandwith is used and the copy happens server side. Even though our pipeline will be slower because it is sync, we won't need to poll for progress and we can just monitor the queue for pending and failed (this monitoring was our issue with the async copy). 
- Since our use case is for many small blobs, we can move the whole blob in one block and then make the additional call to commit the block. This (plus the queue retry) should simplify the resume/progress code a lot.
- I tested this approach today(queue --> Azure Function to copy via PutBlockFromUrl) approach with 90k blobs and it seems to work although a little slow at a peak of 200 blobs/sec. This throughput depends a lot on the function scale out so the throughput may increase with more queue items in the queue.

Thanks again for all your help and timely responses. I think we have enough information to go on at this point.
