### ISSUE TITLE
'CloudBlobContainer' exists in both Microsoft.Azure.Storage.Blob and Microsoft.WindowsAzure.Storage

### ISSUE THREAD

**Issue by Efreeto** [Azure/azure-storage-net-data-movement#159]
### Which service(blob, file) does this issue concern? 
CloudBlobContainer
 
### Which version of the SDK was used?
0.9.0

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.Net Framework 2.0

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
Install both "Microsoft.Azure.Storage.DataMovement" Version="0.9.0"
and "Microsoft.Azure.Storage.Blob" Version="9.4.2" from nuget.
Microsoft.Azure.Storage.DataMovement is dependent on the old version of "Microsoft.WindowsAzure.Storage", but they moved to the new version of "Microsoft.Azure.Storage.Blob"
 
### What problem was encountered?
Compiler error: 'CloudBlobContainer' exists in both Microsoft.Azure.Storage.Blob and Microsoft.WindowsAzure.Storage

**Comment by MarcoK80** [comment]
Same issue with AspNetCore: 
The type 'CloudBlockBlob' exists in both 'Microsoft.Azure.Storage.Blob, Version=9.4.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.WindowsAzure.Storage, Version=8.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

Seems Microsoft.AspNetCore.DataProtection.AzureStorage 2.2.0 referenced the old versions.

![image](https://user-images.githubusercontent.com/43368445/51590910-e3d44d00-1eeb-11e9-8d91-44a38dda4df0.png)

**Comment by blueww** [comment]
@MarcoK80 
You might should open the issue for "Microsoft.AspNetCore.DataProtection.AzureStorage" to that SDK owner. This GitHub repo is for DMlib.
Thanks for your understanding!

**Comment by hamdyghanem** [comment]
Same issue here, when you I try to use : "Microsoft.Azure.Storage.DataMovement" package
in a project that has "Microsoft.NET.Sdk.Functions" package
I have the 

Error	CS0433	The type 'CloudBlockBlob' exists in both 'Microsoft.Azure.Storage.Blob, Version=9.4.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.WindowsAzure.Storage, Version=9.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	KSparkRemoteServer

**Comment by hamdyghanem** [comment]
Same issue here, when you I try to use : "Microsoft.Azure.Storage.DataMovement" package
in a project that has "Microsoft.NET.Sdk.Functions" package
I have the
Error CS0433 The type 'CloudBlockBlob' exists in both 'Microsoft.Azure.Storage.Blob, Version=9.4.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.WindowsAzure.Storage, Version=9.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by blueww** [comment]
[DMlib 0.10.1 ](https://github.com/Azure/azure-storage-net-data-movement/releases/tag/v0.10.1)has released to support new Azure Storage Client library 9.4.2. (the new library split to Blob/Queue/File, like Microsoft.Azure.Storage.Blob)
To use the new DMlib, you need to first uninstall the old Azure Storage Client library "Microsoft.WindowsAzure.Storage", then install new DMlib.

If you have other SDK reference old  Azure Storage Client library (9.3.* or early), you need to either:
1.  Upgrade other SDK to new version which support new Azure Storage Client library (9.4.* or later)
2. If other SDK don't support new storage library, need use old DMlib (0.9.0 or early) until other SDK upgraded.

**Comment by vivekjainAco** [comment]
I still have this issue: 

The type 'BlobContainerPermissions' exists in both 'Microsoft.Azure.Storage.Blob, Version=9.4.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.WindowsAzure.Storage, Version=8.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by blueww** [comment]
@vivekjainAco 
You can see in https://github.com/Azure/azure-storage-net-data-movement/blob/ecfadcb4da1b0631698854f241a3a8503b670386/BreakingChanges.txt#L4
You need first uninstall 'Microsoft.WindowsAzure.Storage', then install dmlib 0.10.0

**Comment by blueww** [comment]
@vivekjainAco
Close this issue as not see the comments from you for a long time.
Feel free to contact us again if need more assistance.
