### ISSUE TITLE
Basic authentication (username:password) for URL in TransferManager.CopyAsync

### ISSUE THREAD

**Issue by nitrif** [Azure/azure-storage-net-data-movement#161]
Hi,

I wanted to copy images stored on external URLs to our Azure storage account and intended to use TransferManager.CopyAsync(...) command. The images are accessed with basic username:password authentication, so I created Uris with format "https://usrname:pass@...". I receive following exception:

 | InnerException | {"The remote server returned an error: (401) Unauthorized."} | System.Exception {Microsoft.WindowsAzure.Storage.StorageException}

which I think comes from unsuccessful image URL authentication. Is it possible to to retrieve images behind basic authentication?

I use VS 2017, .NET Framework 4.6.1, Microsoft.Azure.Storage.DataMovement Nuget package 0.9.0

Thanks,
Nikola

**Comment by blueww** [comment]
@nitrif 

DMlib has 2 kinds of copy:
1. SyncCopy (isServiceCopy=false): the copy is actually download from Azure and upload to Azure, and source must be Azure Blob/Azure File
2. Asynccopy (isServiceCopy = true): use the Rest API https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob to do Azure Blob/File server side Copy . 

I suspect you use Server side Copy. With the [rest api doc](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob), you can see `x-ms-copy-source` should be Blob or Azure file. So the  external URLs should not be officially supported. 

Besides this, Could you test your URI with format "https://usrname:pass@...", Can you download it with IE? If not, it should can't be copy to blob/AzureFile by AsyncCopy.

If you just want to copy the files to Azure Blob, Can you first download it to local file, then upload to Azure with DMlib?

**Comment by nitrif** [comment]
Yes, I used Asynccopy (Server side Copy), since I need to transfer a lot of data with high bandwidth (no local proxy). IE cannot download the format, Firefox and Chrome can.
What could be the alternative? Azure Batch service?

**Comment by blueww** [comment]
As IE can't download it, this should can't be copy by Asynccopy.
Is that possible that you download it to local files, and then upload with DMlib?

**Comment by nitrif** [comment]
Upload of local files using TransferManager.UploadAsync() works if that is what you ask.

**Comment by blueww** [comment]
Then to workaround your issue,  Could you download the images with your own code, and then upload with DMlib?

**Comment by blueww** [comment]
@nitrif 
I can usderstand you requirement for copy the images with high throughput.

But as the URI can't be supported as server side copy Source, it can't be copy directly from source to Azure Server. (I will write mail to Client team to confirm it).
If so, the only way I can think of is downloading it by yourself and then uploading it to Azure. (I will ask our PM if they have any other idea) If you really want high bandwidth, you might can try to separate the work to several machines, to run the download/upload parallelly, so the transfer will be faster then single machine. You might can setup Azure VM in the same region with the Storage Account, then the upload speed will be fast.

**Comment by nitrif** [comment]
Thanks. It seems I should try [Batch](https://azure.microsoft.com/en-us/services/batch/) next.

**Comment by blueww** [comment]
@nitrif 
Thanks for your understanding! 
I don't get better idea for this issue from our PM and Client team.

As you will try batch, I will close the issue now.
Feel free to contact us if you need any other support from us.
