### ISSUE TITLE
Conflict: 'Microsoft.Azure.Storage.Blob, Version=9.4.2.0 neutraland 'Microsoft.WindowsAzure.Storage, Version=9.3.1.0

### ISSUE THREAD

**Issue by hamdyghanem** [Azure/azure-storage-net-data-movement#166]
I have a .netCore 2.2 Application which has "Microsoft.NET.Sdk.Functions" package

when you I try to use : "Microsoft.Azure.Storage.DataMovement" package to the project I have the following error:

Error CS0433 The type 'CloudBlockBlob' exists in both 'Microsoft.Azure.Storage.Blob, Version=9.4.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.WindowsAzure.Storage, Version=9.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by blueww** [comment]
@hamdyghanem 
Which version of DMlib do you use? is it 0.10.1?
I have answered  the question in https://github.com/Azure/azure-storage-net-data-movement/issues/159

[DMlib 0.10.1 ](https://github.com/Azure/azure-storage-net-data-movement/releases/tag/v0.10.1)has released to support new Azure Storage Client library 9.4.2. (the new library split to Blob/Queue/File, like Microsoft.Azure.Storage.Blob)
To use the new DMlib, you need to first uninstall the old Azure Storage Client library "Microsoft.WindowsAzure.Storage", then install new DMlib.

If you have other SDK reference old  Azure Storage Client library (9.3.* or early), you need to either:
1.  Upgrade other SDK to new version which support new Azure Storage Client library (9.4.* or later)
2. If other SDK don't support new storage library, need use old DMlib (0.9.0 or early) until other SDK upgraded.

You might can file an issue for "Microsoft.NET.Sdk.Functions" in https://github.com/aspnet/AspNetCore , for this SDK to upgrade to new Storage Client library.

**Comment by hamdyghanem** [comment]
@blueww 
1- I have to upgrade and I did 
2-as a workaround, for now, I created two projects, one uses the 9.4 and the other which reference the sdk functions which uses the 9.3

**Comment by blueww** [comment]
@hamdyghanem 
The latest "Microsoft.NET.Sdk.Functions" 1.0.26 reference Storage Client library (aka: XSCL) 9.3.1, but the latest "Microsoft.Azure.Storage.DataMovement" reference XSCL 9.4.2, so the conflict happen.

the project site for "Microsoft.NET.Sdk.Functions" is  https://github.com/Azure/azure-functions-vs-build-sdk/issues. (sorry the lin)

There's a way can make project reference same namespace from difference projects, if you’re developing cmdlets in C#: https://stackoverflow.com/questions/517058/how-to-reference-a-namespace-from-a-specific-assembly 

I have made it work in my project by following code change:
Add following to netcore csproj file:

```
  <Target Name="ChangeAliasesOfStrongNameAssemblies" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'Microsoft.Azure.Storage.Blob'">
        <Aliases>xsclblob</Aliases>
      </ReferencePath>
      <ReferencePath Condition="'%(FileName)' == 'Microsoft.Azure.Storage.Queue'">
        <Aliases>xsclqueue</Aliases>
      </ReferencePath>
      <ReferencePath Condition="'%(FileName)' == 'Microsoft.Azure.Storage.File'">
        <Aliases>xsclfile</Aliases>
      </ReferencePath>
      <ReferencePath Condition="'%(FileName)' == 'Microsoft.Azure.Storage.Common'">
        <Aliases>xsclcommon</Aliases>
      </ReferencePath>
      <ReferencePath Condition="'%(FileName)' == 'Microsoft.WindowsAzure.Storage'">
        <Aliases>xsclold</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
```


And then we can reference objects in different version XSCL by:
```
extern alias xsclcommon; 
extern alias xsclblob;
extern alias xsclold; 
using StorageTable = xsclold::Microsoft.WindowsAzure.Storage.Table;
using xsclcommon ::Microsoft.WindowsAzure.Storage;
using xsclblob:: Microsoft.WindowsAzure.Storage.Blob;

StorageTable.CloudTable = …
CloudBlob= …
```

**Comment by blueww** [comment]
@hamdyghanem 
Close this issue as not see the comments from you for a long time.
Feel free to contact us again if need more assistance.
