### ISSUE TITLE
Unable to download files from Azure File directory in a single stream using DownloadDirectoryAsync

### ISSUE THREAD

**Issue by noemi616** [Azure/azure-storage-net-data-movement#167]
### Which service(blob, file) does this issue concern? 
Azure Files
 
### Which version of the SDK was used?
v 0.10.1

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.NET Core 2.1
Windows 10

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
I am writing a test console app that tries to download the file share on a single stream.  However, I am not able to do so when download subdirectories, see code below.

 static string fileshareName = "testfileshare";
 static string fsDirName = "testfsdir";
         static string accountName = "<accountname>";
        static string accountKey = "<accountKey>";
        static string localDirectoryPath = "<localdirPath>";
        static bool isRecursive = true;

        public static void Main()
        {

            Console.WriteLine("Storage account name: {0}", accountName);
            Console.WriteLine("Storage account key: {0}", accountKey);

            string storageConnectionString = "DefaultEndpointsProtocol=https;AccountName=" + accountName + ";AccountKey=" + accountKey;
            CloudStorageAccount account = CloudStorageAccount.Parse(storageConnectionString);

            TransferFileShareToLocalDirectory(account).Wait();

            Console.ReadKey();
        }

        public static CloudFileDirectory GetFileShare(CloudStorageAccount account)
        {

            Console.WriteLine("Name of File share: {0}", fileshareName);
            CloudFileClient fileClient = account.CreateCloudFileClient();
            CloudFileShare cloudFileShare = fileClient.GetShareReference(fileshareName);
            CloudFileDirectory cloudFileDir = null;

            if (string.IsNullOrEmpty(fsDirName))
                cloudFileDir = cloudFileShare.GetRootDirectoryReference();
            else
                cloudFileDir = new CloudFileDirectory(new Uri(@"https://cont2stor180131.file.core.windows.net/testfileshare/" + fsDirName));

            return cloudFileDir;
        }

        public static async Task TransferFileShareToLocalDirectory(CloudStorageAccount account)
        {
            string destPath = new System.IO.DirectoryInfo(localDirectoryPath).CreateSubdirectory(fileshareName).FullName;
            Console.WriteLine("\nDestination Path: {0}", destPath);

            CloudFileDirectory fileDirectory = GetFileShare(account);
            TransferCheckpoint checkpoint = null;
            DirectoryTransferContext context = GetDirectoryTransferContext(checkpoint);
            CancellationTokenSource cancellationSource = new CancellationTokenSource();
            Console.WriteLine("\nTransfer started...\nPress 'c' to temporarily cancel your transfer...\n");

            Stopwatch stopWatch = Stopwatch.StartNew();
            Task task;
            ConsoleKeyInfo keyinfo;
            DownloadDirectoryOptions options = new DownloadDirectoryOptions()
            {
                Recursive = isRecursive
            };

            try
            {
                task = TransferManager.DownloadDirectoryAsync(fileDirectory, destPath, options, context, cancellationSource.Token);

                while (!task.IsCompleted)
                {
                    if (Console.KeyAvailable)
                    {
                        keyinfo = Console.ReadKey(true);
                        if (keyinfo.Key == ConsoleKey.C)
                        {
                            cancellationSource.Cancel();
                        }
                    }
                }
                await task;
            }
            catch (Exception e)
            {
                Console.WriteLine("\nThe transfer is canceled: {0}", e.Message);
            }

            if (cancellationSource.IsCancellationRequested)
            {
                Console.WriteLine("\nTransfer will resume in 3 seconds...");
                Thread.Sleep(3000);
                checkpoint = context.LastCheckpoint;
                context = GetDirectoryTransferContext(checkpoint);
                Console.WriteLine("\nResuming transfer...\n");
                await TransferManager.DownloadDirectoryAsync(fileDirectory, destPath, options, context);

            }

            stopWatch.Stop();
            Console.WriteLine("\nTransfer operation completed in " + stopWatch.Elapsed.TotalSeconds + " seconds.");

        }

        public static SingleTransferContext GetSingleTransferContext(TransferCheckpoint checkpoint)
        {
            SingleTransferContext context = new SingleTransferContext(checkpoint);

            context.ProgressHandler = new Progress<TransferStatus>((progress) =>
            {
                Console.Write("\rBytes transferred: {0}", progress.BytesTransferred);
            });

            return context;
        }

        public static DirectoryTransferContext GetDirectoryTransferContext(TransferCheckpoint checkpoint)
        {
            DirectoryTransferContext context = new DirectoryTransferContext(checkpoint);

            context.ProgressHandler = new Progress<TransferStatus>((progress) =>
            {
                Console.Write("\rBytes transferred: {0}", progress.BytesTransferred);
            });

 I even tried playing with the DownloadDirectoryOptions where I set recursive to false and search pattern to capture all TXT files (the subdirectory I'm testing has only txt files) but still not able to download those files (though I no longer get an error)

DownloadDirectoryOptions options = new DownloadDirectoryOptions()
            {
                Recursive = false,
                SearchPattern = "*.txt" //or "*.*"
            };

### What problem was encountered?

I am getting "Failed to enumerate directory https://<accountname>.file.core.windows.net/testfileshare/testfsdir with file pattern ." error 
 

### Have you found a mitigation/solution?
No

**Comment by EmmaZhu** [comment]
@noemi616  

The issue is because it uses following code to get file directory instance which doesn't include any credentials.
`            cloudFileDir = new CloudFileDirectory(new Uri(@"https://cont2stor180131.file.core.windows.net/testfileshare/" + fsDirName));` 

It should be able to work well to use following line to get directory instance:
`cloudFileDir = cloudFileShare.GetRootDirectoryReference().GetDirectoryReference(fsDirName);`

**Comment by noemi616** [comment]
HI @EmmaZhu  - this did the trick - thanks!
