### ISSUE TITLE
Reference to type 'CloudFile' claims it is defined in 'Microsoft.Azure.Storage.File'

### ISSUE THREAD

**Issue by nmg77** [Azure/azure-storage-net-data-movement#168]
Just upgraded to the latest Microsoft.Azure.Storage.File (and other libraries) and it appears to have broken the TransferManager.

E.g. TransferManager.UploadAsync(fileName, blockBlob)) won't compile.

**Comment by EmmaZhu** [comment]
We are planning for a release to upgrade v10 of Microsoft.Azure.Storage.File and Microsoft.Azure.Storage.Blob. Will update you when the release is ready.

**Comment by EmmaZhu** [comment]
We've released a new DataMovement Library: 0.11.0 to upgrade to package of Microsoft.Azure.Storage.Blob and Microsoft.Azure.Storage.File with version 10.0.1. Would you like to have a try?
