### ISSUE TITLE
TransferManager.CopyDirectoryAsync Error 

### ISSUE THREAD

**Issue by smoro88** [Azure/azure-storage-net-data-movement#170]
source / destination are CloudFileDirectory objects.

var result = await TransferManager.CopyDirectoryAsync(sourceFolder, destFolder, true, new CopyDirectoryOptions { Recursive = true }, new DirectoryTransferContext());
    
Build Fails with latest 10.0.1 with the following error on above line.      
 Error CS7069: Reference to type 'CloudBlobDirectory' claims it is defined in 'Microsoft.Azure.Storage.Blob', but it could not be found (CS7069) 
Error CS7069: Reference to type 'CloudFileDirectory' claims it is defined in 'Microsoft.Azure.Storage.File', but it could not be found (CS7069)

**Comment by blueww** [comment]
@smoro88 
We are working on a release to upgrade to v10 of Microsoft.Azure.Storage.File and Microsoft.Azure.Storage.Blob. 

We already have issue https://github.com/Azure/azure-storage-net-data-movement/issues/169 to track this upgrade. 
Do you mind if we close this one as they target for same issue?
Feel free to let us know if you have any further questions.

**Comment by smoro88** [comment]
Sure I will track progress of 169 and you can close this issue.
