### ISSUE TITLE
DataMovement.TransferManager.UploadAsync  a lot slower then AzCopy

### ISSUE THREAD

**Issue by scottbright22** [Azure/azure-storage-net-data-movement#175]
### Which service(blob, file) does this issue concern? 
Blob
 
### Which version of the SDK was used?
Microsoft.Azure.Storage.DataMovement  (0.11.0)
Microsoft.Azure.Storage.Blob, Microsoft.Azure.Storage.File, Microsoft.Azure.Storage.Common (10.0.1)

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.Net 4.5.2

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.

Microsoft Azure Storage Data Movement Library (0.11.0)

Using DataMovement.TransferManager.UploadAsync we are unable to get even close to the speed of the command line version of AzCopy.
Our times look to be even slower than AzCopy when we set /NC:1

Are we using it wrong, or missing a setting?
 
AzCopy Command Line:

8.1.0 : AzCopy /Y /V /Source:. /Dest:https://xxxx.blob.core.windows.net/poly /DestKey:****** /Pattern:test2.zip /NC:64 /Z:.

.Net Code:

    Async Function CopyFile() As Task

        Try

            Dim filepath As String = "d:\azure\test-azc-1.zip"
            Dim blobName As String = Path.GetFileName(filepath)

            ServicePointManager.Expect100Continue = False
            DataMovement.TransferManager.Configurations.ParallelOperations = 64
            ServicePointManager.DefaultConnectionLimit = 64

            Dim storageAccount As Storage.CloudStorageAccount
            storageAccount = CloudStorageAccount.Parse(CurProject.Storage.StorageBlobConnectionString)
            Dim TestBlobclient As Storage.Blob.CloudBlobClient = storageAccount.CreateCloudBlobClient()
            Dim TestBlobcontainer As CloudBlobContainer = TestBlobclient.GetContainerReference(CurProject.Storage.BlobContainerName)
            Dim blobtoUpload As Storage.Blob.CloudBlockBlob = TestBlobcontainer.GetBlockBlobReference(blobName)

            AZB_Status_Message("Upload Started for File:" & filepath)

            Await DataMovement.TransferManager.UploadAsync(filepath, blobtoUpload)

            AZB_Status_Message("Upload Completed for File:" & filepath)

        Catch ex As Exception
            AZB_Status_Message(GetExceptionMsg(ex, GetMethodName), True)
        End Try

    End Function

### What problem was encountered?
Slow Upload Speed using DataMovement.TransferManager.UploadAsync
 
### Have you found a mitigation/solution?
Use AzCopy.exe but we want the fast upload in our application.

**Comment by scottbright22** [comment]
We stripped out just the upload function from our app, and put it in a new project.

NOW it goes fast. So something else in the app must be interfering. We will try to track that down....

**Comment by EmmaZhu** [comment]
We are following this issue with Sumanth offline. 

Thanks @scottbright22 for the update.

**Comment by scottbright22** [comment]
Update: 

We stripped out the DataMovement.TransferManager.UploadAsync logic out of our main app and into a stand alone app. This app ran the upload at full speed.

We then went back to our main app and commented things out until we narrowed down what caused the slow data transfer.

Within our app we have a function that connects to the Blob Container. It checks if the container exists by using Blobcontainer.ExistsAsync. 

It turns out that you need to set the ServicePointManager.DefaultConnectionLimit prior to any access to that blob container.  We moved the set of this to before the ExistsAsync and our app now uploads at full speed. 

Setting ServicePointManager.DefaultConnectionLimit right before the upload does not help. The first call to a blob access type function seems to lock inthe value. We were getting the default value of 2 locked in.
