### ISSUE TITLE
Upload blob failed each time after 15 minutes

### ISSUE THREAD

**Issue by epi82** [Azure/azure-storage-net-data-movement#179]
### Which service(blob, file) does this issue concern? 
blob
 
### Which version of the SDK was used?
0.12.0

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.Net Core

### What problem was encountered?
If I have a slow connection upload blob failed each time after 15 minutes with message:
**One or more errors occurred. (The transfer failed.)**

With normal connection the upload works fine. This is my code:
```
CloudBlockBlob blockBlob = new CloudBlockBlob(new Uri(sConnString));
ServicePointManager.Expect100Continue = false;
TransferManager.Configurations.ParallelOperations = 10;
...
var task = TransferManager.UploadAsync(pathFile, blockBlob, null, context, CancellationToken.None);                
task.Wait();

```

How can I solve it? 

### Have you found a mitigation/solution?
No

**Comment by jiacfan** [comment]
Hi, @epi82 

Thanks for reaching us.

In a slow connection, it's much likely to hit network layer issues, and cause retry. And 15 minutes is the default overall timeout for an underline .Net SDK API call, so you might see "If I have a slow connection upload blob failed each time after 15 minutes ".

Would you refer to [BlobDirectoryCopySample](https://github.com/Azure/azure-storage-net-data-movement/blob/d8f127bac0748680275c0fa740dca91cc2032059/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L442) to add retry logic with checkpoint when hitting timeout? The retry logic should be similar to the catch cancel exception and resume the transfer in the given sample.

Thanks,
Jiachen

**Comment by epi82** [comment]
Hi @jiacfan,
I've seen the sample and tried to add a retry logic but it seems not work.

In the catch exception I've added a call to a method for resume the trasfert:

```
...
catch (Exception e) {
ResumeTransfert(context, pathFile, blockBlob);
}

private void ResumeTransfert(SingleTransferContext context, string pathFile, CloudBlockBlob blockBlob)
{
	SingleTransferContext retryContext = context;
	SingleTransferContext resumeContext = null;

	while (true)
	{
		try
		{
			// Store the transfer checkpoint
			TransferCheckpoint checkpoint = retryContext.LastCheckpoint;                    

			// Create a new TransferContext with the store checkpoint
			resumeContext = new SingleTransferContext(checkpoint);
			resumeContext.ProgressHandler = new Progress<TransferStatus>((progress) => {                    
				if (progress.BytesTransferred > 0)
				{
					double byteTransferred = Math.Truncate(ByteSize.FromBytes(progress.BytesTransferred).MegaBytes);
					Log.WriteLog(String.Format("Uploaded: {0} MB", byteTransferred));                            
				}                    
			});

			// Record the overall progress
			ProgressRecorder recorder = new ProgressRecorder();
			resumeContext.ProgressHandler = recorder;

			// Resume transfer from the stored checkpoint
			Console.WriteLine("Resume the cancelled transfer.");
			var task = TransferManager.UploadAsync(pathFile, blockBlob, null, resumeContext);
			task.Wait();

			return;
		}
		catch (Exception e)
		{
			Log.WriteLog("ResumeTransfert: " + e.Message, LogType.Error, LogLevel.Standard);
			retryContext = resumeContext;

			continue;
		}
	}          
}
```

Each time I catch the exception and reupload with the last check point but it doesn't work.
Where I'm wrong?

Thank you.

**Comment by epi82** [comment]
Hi @jiacfan ,
I've tried with a retry logic but it doesn't work...
By the way I find a solution... if I change "ParallelOperations" property with slow connection it works.

From 
`TransferManager.Configurations.ParallelOperations = 10;`
To
`TransferManager.Configurations.ParallelOperations = 2;`

the upload finished without timeout error. 
Now the question is... how I have to set "ParallelOperations"? It depends from the connection speed.

Thank you.

**Comment by jiacfan** [comment]
Hi, Epi82

Nice to know the latest status.  

Yes. Changing ParallelOperations to lower number, helps to keep the number of parallel connections(requests) lower, and this could help to relieve the network pressure and help in your case! The proper number would be related to environment. If the deployment environment is stable, it would be good to do some experiments, and set a number based on experiments' result, and also if the connection speed is stable and testable with program, then it would be good to add some logic to detect connection speed and set ParallelOperations accordingly. 
At same time, retry might still be helpful, for "retry logic but it doesn't work", logically DMLib break down file into chunks, and the checkpoint can record transfer progress per chunk, so during each retry, transfer may progress a bit, while hit network issue again, and need retry again. As I know, there was a potential issue in .Net core's http implementation, where exception fail to be thrown immediately when downstream TCP connection hit problem. And this may cause retry inefficient(i.e. program need wait SDK 15 minute's timeout when such TCP layer network issue happened), while the retry based on checkpoint is still suggested, which helps transfer finishes well.

Thanks,
Jiachen

**Comment by epi82** [comment]
It seems works.
I've tried with a function like this:

```
private int GetParallelOperations(double transfertSpeed)
        {
            int retval = 0;
            switch (transfertSpeed)
            {
                case double n when (n >= 1):
                    retval = Environment.ProcessorCount * 8;
                    break;
                case double n when (n < 1 && n>=0.1):
                    retval = 10;
                    break;                
                default:
                    retval = 2;
                    break;
            }

            return retval;
        }
```

and then used:

`TransferManager.Configurations.ParallelOperations = GetParallelOperations(Utilities.TransferSpeed);`

where transfer speed is stimated with a simple file with size 5MB. For speed test I left "ParallelOperations" set to "Environment.ProcessorCount * 8" (works also in case of slow connection).

**Comment by jiacfan** [comment]
@epi82 Great to know the news! Welcome further discussion if having question.

**Comment by santhoshhere** [comment]
> It seems works.
> I've tried with a function like this:
> 
> ```
> private int GetParallelOperations(double transfertSpeed)
>         {
>             int retval = 0;
>             switch (transfertSpeed)
>             {
>                 case double n when (n >= 1):
>                     retval = Environment.ProcessorCount * 8;
>                     break;
>                 case double n when (n < 1 && n>=0.1):
>                     retval = 10;
>                     break;                
>                 default:
>                     retval = 2;
>                     break;
>             }
> 
>             return retval;
>         }
> ```
> 
> and then used:
> 
> `TransferManager.Configurations.ParallelOperations = GetParallelOperations(Utilities.TransferSpeed);`
> 
> where transfer speed is stimated with a simple file with size 5MB. For speed test I left "ParallelOperations" set to "Environment.ProcessorCount * 8" (works also in case of slow connection).

What is the unit of measure for transferspeed? kbps or mbps and what's the calculation on the switch case? please explain
