### ISSUE TITLE
On the fly decryption of a file(video) while copying blobs 

### ISSUE THREAD

**Issue by nishant09** [Azure/azure-storage-net-data-movement#185]
### Which service(blob, file) does this issue concern? 
blob
 
### Which version of the SDK was used?
Microsoft.Azure.Storage.DataMovement 1.0.0

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.Net framework > 4.5.1 on Windows 10

I'm working on a moderate to big size project where I want to copy/transfer large blobs(tens of thousands of video files) from one storage subscription to another subscription. I can easily use your server-to-server APIs for this work. However, I would like to add one more operation in the middle. That is decryption of these video file since the destination expect only decrypted video file. My question is can I do this decryption operation on the fly just before you paste files in the destination storage account ?

What I'm doing currently is download the video file from the source storage account to local harddrive, decrypt and upload in the destination storage account. Which I want to avoid using because disk throughput and size of the disk issues . Trying to find a in-memory or better option to achieve this goal.

**Comment by jiacfan** [comment]
Hi, @nishant09 

Thanks for reaching us! 

Temporarily DMLib doesn't support transforming data in-the-middle of copy. For such kind of copy, how to validate the integrity after copy finished would be open question to think about(as the data has been changed in middle). 

I think your approach is a good work around, as it can help to ensure data integrity:
- During download, data integrity checked if source file has MD5 tag, and MD5 validation enabled during download. 
- During upload, MD5 will be set after upload finished, which later you can validate if the data has been corrupt during next download. 
- If MD5 validation pass, and data corrupt, possibly figure out there are some problems during transforming logic.

To optimize the speed, possibly consider to:
- use multiple machines, and each handles part of the files.
- temporarily mount some disks(e.g. Azure file SMB disk) for helping, and processing with load balancing using different local disk to fulfill different file transforming tasks.

Best Regards,
Jiachen

**Comment by nishant09** [comment]
Thanks for your reply Jiachen.
How efficient is DMLib for downloading/uploading blobs compare to Microsoft.WindowsAzure.Storage? I'm currently using Microsoft.WindowsAzure.Storage. Do you have any documentation for the comparison?

**Comment by jiacfan** [comment]
Welcome @nishant09. 

DMLib is optimized for parallel upload/download, so it should be generally faster, while it's hard to say what's the detailed mark, considering perf marks may be related to environment, data samples and the configurations you are using. 

Personally, I think it worth a try, and please feel free to contact us if you find any problem. We would be happy to check if in specific scenario DMLib can work better.

BTW, DMLib supports transfer single/directory of files with journal records(i.e. support resume the transfer if transfer failed in the middle), so it's a convenient and reliable way to transfer files.

Best Regards,
Jiachen

**Comment by nishant09** [comment]
Thanks Jiachen
