### ISSUE TITLE
Resume a transfer after service restart

### ISSUE THREAD

**Issue by Planche95** [Azure/azure-storage-net-data-movement#192]
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-data-movement-library

If I want to resume a transfer when some exception occurs I can catch it use checkpoint from SingleTransferContext. 

But what if my service will crash and need a restart? If I stared copy a big file e.g. 1TB and my transfer stopped on 900GB I would like to resume a transfer to reduce the potential costs. Is it possible?

**Comment by EmmaZhu** [comment]
Hi @Planche95 ,

DMLib supports to serialize/deserialize checkpoint. I think you can persist the serialized checkpoint to a file, and deserialize it when you want to resume the transfer.

You can see sample to serializing a checkpoint here: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L503 

Thanks
Emma
