### ISSUE TITLE
Add "CopySourceLastModified" metadata to destination blob

### ISSUE THREAD

**Issue by petr-x** [Azure/azure-storage-net-data-movement#196]
### Which service(blob, file) does this issue concern? 
Destination CloudBlob Metadata
 
### Which version of the SDK was used?
1.1.0

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.net core 3.0

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.

Data Movement library add specific metadata in the destination blob. I'm trying to build incremental backup function which will use code snippet you posted in: #13 

However the destination doesn't contain LastModified metadata from the source as showed in the screenshot:

![image](https://user-images.githubusercontent.com/18548253/69089923-f73b4080-0a48-11ea-9ff5-3093090202bb.png)

Will be possible to add metadata "CopySourceLastModified" which will contain source LastModified value?

### Have you found a mitigation/solution?

The only possible option i found is to set custom metadata (CopySourceLastModified) on the blob after transfer is completed.

**Comment by blueww** [comment]
@petr-x 
You can add the metadata in transferContext.SetAttributesCallbackAsync(). Then it will be set to the dest blob when DMlib copy the blob.
Like following:

```
     transferContext.SetAttributesCallbackAsync = async (destination) =>
     {
          CloudBlob destBlob = destination as CloudBlob;
          //TODO: Get Source Blob LMT like:
          DateTime SourceLastModified = sourceBlob.Properties.LastModified;

          destBlob.Metadata.Add("CopySourceLastModified", SourceLastModified.ToString());
     };
```

**Comment by petr-x** [comment]
That's cool, many thanks!

Here docu reference:
https://azure.github.io/azure-storage-net-data-movement/html/a35d1cbc-7797-21c7-19bc-149d3845ed1a.htm
