### ISSUE TITLE
Very slow transfer on a large assets of small files 

### ISSUE THREAD

**Issue by bryjamus** [Azure/azure-storage-net-data-movement#198]
### Which service(blob, file) does this issue concern? 
We use file service.
I've found related issue #175 but it is closed now.

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
net462, netstandard2.1, netstandard3.1
DataMovement version 1.1.0.11 (from Nuget)
Test was made in Debug and Release mode
Windows 10 Enterprise 1803

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
We prepare folder which has many subfolders, very deep (deep level was > 30), in some of folders are files which are less than 1KB, we have 10000 files.

We use this code to upload folder to AFS:

```
private static async Task DirectoryUploadSample()
{
	SetupTransferService(); // those settings has no meaningful impact on performace

	string path = @"c:\whatever"; // Folder to send

	var destDirectory = await DataMovementSpikeSetup.Fileshare.GetDirectoryAsync("DestinationFolder"); // Create if not exist destination folder on share on Azure

	UploadDirectoryOptions options = new UploadDirectoryOptions
	{
		Recursive = true,
		PreserveSMBAttributes = true
	};

	DirectoryTransferContext context = new DirectoryTransferContext();
	context.ShouldOverwriteCallbackAsync = TransferContext.ForceOverwrite;

	TransferStatus status = await TransferManager.UploadDirectoryAsync(path, destDirectory, options, context);
}

private static void SetupTransferService()
{
	ServicePointManager.DefaultConnectionLimit = Environment.ProcessorCount * 8;
	ServicePointManager.SetTcpKeepAlive(true, 10000, 10000);
	TransferManager.Configurations.ParallelOperations = 64;
	TransferManager.Configurations.BlockSize = Constants.MaxBlockSize;
}
```

 
### What problem was encountered?
Those 10K files was sent with throughput < 1Mbps. I try to figure out was is wrong and I did ETW session. In our case there is almost 99% of time in BLOCKED_TIME:

![1Untitled](https://user-images.githubusercontent.com/7079299/71003093-d36b2900-20e0-11ea-8388-c6b434505c53.png)

Does file enumeration or transfer thread waiting? I don't know. Look at flamegraph how it looks:

![PerfViewData flameGraph1](https://user-images.githubusercontent.com/7079299/71003107-d8c87380-20e0-11ea-9eba-82ce67d8962b.png)

And another view:

![image](https://user-images.githubusercontent.com/7079299/71081584-ce18e780-218f-11ea-90d2-af547e7fa38a.png)

What can we change to handle this properly?
 
### Have you found a mitigation/solution?
No.

**Comment by EmmaZhu** [comment]
Hi @bryjamus ,

Is the method `SetupTransferService()` in your code snippet invoked at the very beginning of your application, before any request is sent? If it is, the slowness should not be caused by the issue your referenced.

To upload a file under a directory, DMLib needs to create the file's parent directory first. For a very deep directory hierarchy, DMLib would need to send one request for each ancient directory of the file, which would need some time. From the statistics result you've shared, seems DMLib did spend most of time waiting on Azure File Directory creation.

Thanks
Emma

**Comment by bryjamus** [comment]
`static void Main() {
  SetupTransferService();
}`

Yest this method is very first. 
Directory structure sounds reasonable. I'll do some test and let you know.

**Comment by bryjamus** [comment]
I repare application which sends data set with 153 files, 159 folders,file sizes 4590 B. I prepare 4 tests:
1. UploadDirectoryAsync - All from DataMovement,
2. Prepare folder structure and use UploadDirectoryAsync
3. Prepare folder structure and use UploadAsync to send all files separately
3. Prepare folder structure and use UploadAsync to send all files but in parallel

First one was the best. So It looks like talking to server and synchronizing folders is slow. Do you have and suggestions how to speedup?

**Comment by EmmaZhu** [comment]
For this issue, we may not have a good solution to speed it up. Before uploading to a file, DMLib needs to send a request to make sure its parent folder's existence. This does require some time. 
In current DMLib, the parent directories creation has already been in parallel. But seems it could still be bottle neck in some case. 
What would think to adjust directory creation's parellel level according to your directory structure?  Would this kind of tunning be efficient in your scenario?

Thanks
Emma

**Comment by bryjamus** [comment]
Hi Emma,
I think we took the unreal case for analysis. In normal work there will be files with different sizes and there won't be directory structure so deep. So I think no tuning is necessary. As you mention directory checking is time consuming in this case. So I think we can close the issue.
Thanks for clarification,
Klaudiusz
