### ISSUE TITLE
Plans on updating to Azure.Storage.Blobs

### ISSUE THREAD

**Issue by macchmie3** [Azure/azure-storage-net-data-movement#206]
### Which service(blob, file) does this issue concern? 
blob
 
Hi, I am using `TransferMenager.CopyAsync(CloudBlob sourceBlob, CloudBlob destBlob, CopyMethod copyMethod)` method from `Microsoft.Azure.Storage.DataMovement`.

Since i am planning to start using `Azure.Storage.Blobs` library in my solution I was wondering if
there any plans on migrating from `Microsoft.Azure.Storage.Blob` to `Azure.Storage.Blobs` in  `Microsoft.Azure.Storage.DataMovement`?

**Comment by jiacfan** [comment]
Thanks for reaching us! My colleague @EmmaZhu might help to provide more suggestions on this.

**Comment by EmmaZhu** [comment]
Hi @macchmie3 ,

We are definitely considering to migrate DMLib to Track2 Client Library, only without detailed plan for now.

If you have seen any conflict or issues when using current DMLib with `Azure.Storage.Blobs` package, could you share the detailed error info? We can help to find a solution or workaround for the issue.

Thanks
Emma

**Comment by macchmie3** [comment]
@EmmaZhu 
I have only seen incompatibility as there is no more a class named "CloudBlob" in Azure.Storage.Blobs, not to mention the assambly changed name. Thanks for your info! :)
