### ISSUE TITLE
A redirected response (HTTP status code 301) from the copy source is not supported. 

### ISSUE THREAD

**Issue by kirk-marple** [Azure/azure-storage-net-data-movement#214]
### Which service(blob, file) does this issue concern? 
Blob
 
### Which version of the SDK was used?
1.3.0

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.NET Core 3.1

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
I'm attempting to transfer/copy a file from a remote URI (http://www.nasa.gov/sites/default/files/thumbnails/image/pia23740.jpg) to my Azure blob storage container.  

It appears this image URI has been redirected (via CloudFront), and that throws an exception with TransferManager.CopyAsync.

**My question is, will this ever be supported via this API?  Is there a technical issue why this isn't possible?**

`        
private async static Task<AzureBlobFileTransferSession> TransferBlobAsync(ILogger logger, IConfiguration configuration, FileTransferConnector connector, FileItem source, FolderItem destination, CancellationToken cancellationToken)
        {
            var sourceUri = new Uri(source.Uri);
            string sourceFilePath = sourceUri.LocalPath;

            var destinationUri = new Uri(destination.Uri);
            string destinationFilePath = destinationUri.LocalPath;

            string accountName = AzureHelpers.ParseStorageAccountName(logger, destinationUri);
            string containerName = AzureHelpers.ParseContainerName(logger, destinationUri);
            string relativePath = AzureHelpers.ParseRelativePath(logger, destinationUri);

            if (String.IsNullOrEmpty(accountName))
                throw new InvalidOperationException("Invalid Azure blob storage account name.");

            if (String.IsNullOrEmpty(containerName))
                throw new InvalidOperationException("Invalid Azure blob storage container name.");

            //
            // NOTE: relative path is optional
            //

            var client = await CreateCloudBlobClientAsync(logger, configuration, connector, accountName);

            var container = client.GetContainerReference(containerName);

            await container.CreateIfNotExistsAsync(cancellationToken);

            string sourceFileName = Path.GetFileName(sourceFilePath);

            CloudBlockBlob destinationBlob;

            if (!String.IsNullOrEmpty(relativePath))
            {
                var destinationDirectory = container.GetDirectoryReference(relativePath);
                destinationBlob = destinationDirectory.GetBlockBlobReference(sourceFileName);
            }
            else
            {
                destinationBlob = container.GetBlockBlobReference(sourceFileName);
            }

            var context = new SingleTransferContext
            {
                //ProgressHandler = Program.ProgressRecorder,
                //ShouldOverwriteCallbackAsync = OverwritePrompt
            };

            var sw = Stopwatch.StartNew();

            await TransferManager.CopyAsync(sourceUri, destinationBlob, true, null, context, cancellationToken);

            var fconnector = new FileConnector();

            fconnector.CopyFrom(connector);

            var file = PopulateFileItem(destinationBlob, fconnector);

            return new AzureBlobFileTransferSession(sourceUri, destinationBlob.Uri, file.Length, sw.Elapsed);
        }
`
 
### What problem was encountered?
System.InvalidOperationException
  HResult=0x80131509
  Message=A redirected response (HTTP status code 301) from the copy source is not supported. The transfer failed. Failed to upload file.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

 
### Have you found a mitigation/solution?

Not yet.  May have to try downloading the image to temp storage first, and then uploading to blob storage.

**Comment by EmmaZhu** [comment]
Hi @kirk-marple ,

Thanks for reporting the issue to us. Copying from a URL outside Azure is actually done by Azure Storage Server, DMLib just send Start Copying request to the server and monitor the copying status. Seems Azure Storage Server doesn't support to copy from a redirect link.

Thanks
Emma

**Comment by kirk-marple** [comment]
Ah gotcha, thanks.  OK closing this issue.
