### ISSUE TITLE
Transfer collection of files/directories within one transfer context

### ISSUE THREAD

**Issue by MarcinKowal** [Azure/azure-storage-net-data-movement#216]
### Which service(blob, file) does this issue concern? 
Fileshare, Blob
 
### Which version of the SDK was used?
1.2.0

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.net 4.6.2, Windows10

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
 I'm trying to upload multiple files, multiple directories and mixed directories and files in the context of one transfer persisted with journal stream. Currently your library exposes single file and single directory (including its subdirectories) transfer. This transfer has its own context serialized to the journal.  How can I achieve functionality uploading multiple files under the same context so it can be easily retried or resumed and DMLib will know which files from input were already transferred. Could transfer context track all these files, or should I call UploadAsync every time with new transfer context created per file I want to upload?        
 
### Have you found a mitigation/solution?

No

**Comment by jiacfan** [comment]
Hi, @MarcinKowal 

Thanks for reaching us. 

TransferContext represents the context for a transfer, and provides additional runtime information about its execution. Maintain transfer context per transfer would be suggested, where it ensures independent journal for differernt transfers, and avoids lock journal for different transfers. Inner Transfermanager, UploadAsync do submit transfer job with given TransferContext, and transfers will be scheduled and fulfilled with single engine.

Best Regards,
Jiachen

**Comment by MarcinKowal** [comment]
@jiacfan thanks for your insight. To be sure if I understood correctly, you recommend reusing transferContext but only for the same transfer SingleDirectory or SingleFile. So how could I implement my case, where I have IEnumerable of directory paths to upload.  See pseudo code below:

- context reused by each directory transfer

`var stream = new FileStream();
 var transferContext = new DirectoryTransferContext(stream);
foreach(var dirPath in directoryPaths)
{
  TransferManager.UploadDirectoryAsync(dirPath, destination, options, transferContext, cancellationToken);
}`

-  context created for each directory transfer

`var stream = new FileStream();
foreach(var dirPath in directoryPaths)
{
   var transferContext = new DirectoryTransferContext(stream);
TransferManager.UploadDirectoryAsync(dirPath, destination, options, transferContext, cancellationToken);
}`

**Comment by jiacfan** [comment]
Hi, MarcinKowal

Thanks for the reply. And sorry for the latency here. Here're more [samples](https://github.com/Azure/azure-storage-net-data-movement/blob/510bd1591f53e4d5da1b9f9ab57e72b6490c4a19/samples/DataMovementSamples/DataMovementSamples/Samples.cs) about using transfercontext. And please check if there is suitable case for your user scenario.  

Thanks,
Jiachen

**Comment by jiacfan** [comment]
Close the issue considering it's 1 month since last rely, and feel free to let us know if there are more problems.
