### ISSUE TITLE
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

### ISSUE THREAD

**Issue by spikeone83** [Azure/azure-storage-net-data-movement#218]
### Which service(blob, file) does this issue concern? 
Blob
 
### Which version of the SDK was used?
Microsoft.Azure.Storage.DataMovement 1.3.0

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.net Framework 4.6.1 running as an AppService on Azure

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
            SingleTransferContext context = new SingleTransferContext();
            var task = TransferManager.CopyAsync(sourceBlob, destinationBlob, CopyMethod.ServiceSideAsyncCopy, null, context, CancellationToken.None);
            await task;
 
### What problem was encountered?
The file will not copy, we get the error message on every file we try to copy. We are trying to migrate to DataMovement instead of using our older method: _blobDestination.StartCopy(blobSource);_ which worked great. We are using the Azure Storage Key with a ConnectionString
 
### Have you found a mitigation/solution?
No, tried everything, tried sample code and still can't get it to work. Solutions seem to say to check computer time but both services are running on Azure (AppService and Storage) and both are in same location

**Comment by blueww** [comment]
@spikeone83 

The error is from server. 
Would you please get the detail request ID from the exception or it's inner exception, then we can do further investigation?

**Comment by spikeone83** [comment]
@blueww 

**HResult**: -2146233088

**InnerException**: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

**StackTrace**:
`   à Microsoft.Azure.Storage.DataMovement.TransferScheduler.<ExecuteJobInternalAsync>d__28.MoveNext() dans C:\Local\Jenkins\jobs\DMLib_1.3.0\workspace\lib\TransferScheduler.cs:ligne 239
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.Azure.Storage.DataMovement.SingleObjectTransfer.<ExecuteAsync>d__17.MoveNext() dans C:\Local\Jenkins\jobs\DMLib_1.3.0\workspace\lib\TransferJobs\SingleObjectTransfer.cs:ligne 257
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.Azure.Storage.DataMovement.TransferManager.<DoTransfer>d__92.MoveNext() dans C:\Local\Jenkins\jobs\DMLib_1.3.0\workspace\lib\TransferManager.cs:ligne 1743
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à ConsoleApp1.Program.<MovePhoto>d__8.MoveNext() dans D:\DEV\TestDataMovement\ConsoleApp1\ConsoleApp1\Program.cs:ligne 101`

**Comment by blueww** [comment]
@spikeone83
The error is fail to access the source blob,
Server log to access source blob shows : "Microsoft.Cis.Services.Nephos.Common.Authentication.AuthenticationFailureException : Signature did not match. "

So it seems the SAS credential in "sourceBlob" doesn't have permission to read from the source blob. 
Would you please share how you generated the "sourceBlob"  object? especially if it's in SAS credential, how you generated the SAS.
And would you please try to GetProperties from the "sourceBlob" object, and see if it can success?

**Comment by spikeone83** [comment]
It seems that all along, the problem was my container name: it had a trailing "/" which was causing all the trouble.

No idea why but:

```
var container = "container/"
var blobSource = containerSource.GetBlockBlobReference(url) => returned ok
blobSource.FetchAttributes() => returned ok
blobSource.Exists() => returned true
blobDestination.StartCopy(blobSource) => worked

TransferManager.CopyAsync(blobSource, blobDestination, CopyMethod.ServiceSideAsyncCopy, null, context, CancellationToken.None) => failed

```
Once I removed the trailing "/" so "container/" became "container", all worked, it seems like it failed to get a valid SAS Signature to do the transfer with the trailing "/". Why does it work with CopyAsync? I have no idea

At least it works now, I appreciate the help!

**Comment by blueww** [comment]
@spikeone83 
Thanks for the update!
Good to know it works for you now. 

"container/" is not a valid container name, see [link ](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names), so it might cause unexpected behavior.

I will close the issue as you are not blocked now.
Feel free to contact us again if need any further assistance.
