### ISSUE TITLE
Is `sync` operation supported?

### ISSUE THREAD

**Issue by pawelpabich** [Azure/azure-storage-net-data-movement#219]
### Which service(blob, file) does this issue concern? 

Azure Files
 
### Which version of the SDK was used?

1.13

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)

.NET Core 3.1

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.

The main page says that this library backs the `azcopy cli`.  Azcopy cli supports `sync` operation. Does Data Movement library support it? https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync?toc=/azure/storage/blobs/toc.json

**Comment by pawelpabich** [comment]
Alternatively,  is there a way to configure `CopyDirectoryAsync` to copy only new/changed files?

**Comment by EmmaZhu** [comment]
Hi @pawelpabich ,

You can leverage the ShouldTransferCalbackAsync to filter out files you don't want to copy:

```
                DirectoryTransferContext context = new DirectoryTransferContext();
                context.ShouldTransferCallbackAsync = async (source, destination) =>
                {
                    // Can add more logic here to evaluate whether really need to transfer the target.
                    return true; // Return a bool value to indicate whether to copy the file.
                };
```

Classes of source and destination in the `ShouldTransferCallbackAsync`  would be `CloudFile` for copying from `CloudFileDirectory` to `CloudFileDirectory`.

Thanks
Emma

**Comment by pawelpabich** [comment]
Thanks, @EmmaZhu.  

At the moment I'm using `CopyMethod.ServiceSideAsyncCopy`.  Would specifying this callback make the whole process slower because the server needs to callback to my code for every single file?

**Comment by EmmaZhu** [comment]
The callback is called from local which won't make the process slower.  For your scenario, you may need to send request to check destination's existence, source and destination's last modified time which may cost some time and make the process slower.

Thanks
Emma

**Comment by pawelpabich** [comment]
@EmmaZhu  I ran a small test with 500 files and results are as I expected. 

1. Transferring 500 files took **22 seconds**. 
2. Calling `FetchAttributes(); on `source` and `destination` in `ShouldTransferCallbackAsync` in order to figure out whether files need to be transferred and transferring no files took **42 seconds**.

My conclusion is that doing this check, at least in user code, is expensive. 

Thank you for your help.
