### ISSUE TITLE
Large Memory Use of `Microsoft.Azure.Storage.DataMovement.MemoryManager+MemoryCell` Found After Call to `TransferManager.UploadDirectoryAsync`

### ISSUE THREAD

**Issue by Mike-E-angelo** [Azure/azure-storage-net-data-movement#248]
### Which service(blob, file) does this issue concern? 
blob
 
### Which version of the SDK was used?
https://www.nuget.org/packages/Microsoft.Azure.Storage.DataMovement/2.0.1

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
Windows 10 19041.685 / .NET5.0

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
``` ConsoleApp3.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Storage.DataMovement" Version="2.0.1" />
  </ItemGroup>
</Project>

```

```
	class Program
	{
		static async Task Main(string[] args)
		{
			var container = CloudStorageAccount.Parse("UseDevelopmentStorage=true")
			                                   .CreateCloudBlobClient()
			                                   .GetContainerReference("containername");
			await container.CreateIfNotExistsAsync();
			var directory = container.GetDirectoryReference(string.Empty);
			var context = new DirectoryTransferContext();

			var source =
				@"C:\path\to\directory";
			var options = new UploadDirectoryOptions { Recursive = true };
			var result = await TransferManager.UploadDirectoryAsync(source, directory, options, context)
			                                  .ConfigureAwait(false);
			Console.WriteLine("Hello World!");
		}
	}
```
 
### What problem was encountered?
In my case, a simple directory consisting of 20 files and 8 directories, for a total of 5.14MB managed to produce over 100MB of memory usage via `Microsoft.Azure.Storage.DataMovement.MemoryManager+MemoryCell` instances.  By copying this directory 10 times and retrying again, the process then managed to take over 300MB of memory.  Screenshot of this here:

![](https://i.imgur.com/1DDqrmN.png)
 
### Have you found a mitigation/solution?

Nope, wanted to report it here to make sure it's a known issue.  Everything else works great.  :)

**Comment by blueww** [comment]
@Mike-E-angelo 
For the ~100MB memory for 20 files + 8 folders, as DMlib allocate the memory by the unit of 4MB, so to transfer 20 files parallel, we can allocate 20 * 4MB memory, please the metadata, it might can reach 100MB. 

For transfer 10 times get 300MB, would you please share : do you wait for the first transfer finish, then do the 2nd transfer? If run the transfer jobs parallel, it might cause more memory be allocated.

Anyway, DMlib has a up limitation for the allocated memory, for a 8 core machine, with default configure, the memory allocated for blob content can reach ~800MB, plus metadata, can be a little more than 800 MB.

**Comment by Mike-E-angelo** [comment]
OK cool.  Thank you for taking the time to explain that @blueww.  My primary concern was to ensure that this was a known issue and that everything was operating as expected (and of course if not then to fix it 😁).  Hopefully, this issue can be discovered by others who run into the same question.

Thanks again for your assistance and Happy Holidays to everyone out there. 🎅🎄❄
