### ISSUE TITLE
How are MD5 mismatches handled?

### ISSUE THREAD

**Issue by cjimenezCT** [Azure/azure-storage-net-data-movement#249]
### Which service(blob, file) does this issue concern? 
File

Hello,

I have requirements to automatically validate MD5 hashes when uploading and downloading to/from Azure File Shares. I need to handle MD5 mismatches in some way (probably retries and user input), but I don't know what's already supported in the library.

From what I've read on uploads, files are broken down into blocks, each with their own MD5 that is checked during the transfer, with the ContentMD5 property of the file itself set afterwards. Downloads simply compare the ContentMD5 property between the downloaded file and the file in Azure. Do I understand it correctly?

How exactly are mismatches handled during/after transfers? Does DMLib attempt to retry individual block uploads? Is an exception thrown or an error code returned on a mismatch? Are there multiple potential points of failure I need to account for?

**Comment by blueww** [comment]
@cjimenezCT 

> From what I've read on uploads, files are broken down into blocks, each with their own MD5 that is checked during the transfer, with the ContentMD5 property of the file itself set afterwards. 
[Wei] correct

> Downloads simply compare the ContentMD5 property between the downloaded file and the file in Azure. 
[Wei] Correct, if you don't set "DownloadOptions/DownloadDirectoryOptions.DisableContentMD5Validation" to true.

> How exactly are mismatches handled during/after transfers? Does DMLib attempt to retry individual block uploads? Is an exception thrown or an error code returned on a mismatch?
[Wei] For single chunk MD5 mismatch, DMlib won't retry, but just fail the single file transfer. If you wait on the transfer job, will see exception. 
For whole file MD5 mismatch in download, also won't retry. The file is actually already downloaded, but the transfer job will fail. If you wait on the transfer job, will see exception.

>  Are there multiple potential points of failure I need to account for?
[Wei] Actually, we seldom see the chunk level MD5 mismatch happen in testing DMlib. For whole file MD5 mismatch, need consider if user doesn't set MD5 in upload scenario, and allows user not check it.

**Comment by blueww** [comment]
@cjimenezCT
Close this issue as not hear any responds from you for a long time.
