### ISSUE TITLE
The transfer's minimum timeout doesn't depend on configuration

### ISSUE THREAD

**Issue by KamilKalitaRel** [Azure/azure-storage-net-data-movement#251]
### Which service(blob, file) does this issue concern? 
Both Blob and Fileshare
 
### Which version of the SDK was used?
Microsoft.Azure.Storage.DataMovement.2.0.0

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.NETCoreApp 3.1, .NETFramework 4.6.2

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
Set the configuration e.g.:
```
new BlobRequestOptions
{
	MaximumExecutionTime = TimeSpan.FromMinutes(1),
	ServerTimeout = TimeSpan.FromSeconds(5)
};
```
Start the transfer with DMLib and cut off the Internet connection in the middle.
 
### What problem was encountered?
The transfer hangs for 9-14 minutes, regardless of the configuration.
 
### Have you found a mitigation/solution?
No.

It can be troublesome in case of small transfers, when our users expect the instant feedback.

Also we noticed, that in case of poor Azure Services availability, there's no information which files particularly failed to be transferred (their number is returned from the function, but there are no specific messages/events/exceptions in the meanwhile).

**Comment by blueww** [comment]
@KamilKalitaRel

The “MaximumExecutionTime” and "ServerTimeout"  in "BlobRequestOptions" is for single request, not for the whole transfer. The whole transfer can include many requests depends on the file count/size. So the whole transfer time can be much longer than the “MaximumExecutionTime” and "ServerTimeout" defined in "BlobRequestOptions". And if any single request exceed the “MaximumExecutionTime ” or "ServerTimeout ", DMlib will throw exception. So if you don't see any exception throw in the transfer, it normally means all requests are within the “MaximumExecutionTime” and "ServerTimeout".

If you want the whole transfer be finished in some time (stop the transfer if timeout), you can use the CancellationToken to cancel the transfer after some time. Like following sample shows the upload will be cancel if not finish in 1 minute.
```
CancellationTokenSource cancellationTokenSource= new CancellationTokenSource();
cancellationTokenSource.CancelAfter(60000);

 var task = TransferManager.UploadDirectoryAsync(source, directory, options, context, cancellationTokenSource.Token);
task.Wait();
```

Besides that, as you say "The transfer hangs for 9-14 minutes". Why you think it's hang? You don't see any progress in the time, or no network traffic in the time?

**Comment by KamilKalitaRel** [comment]
@blueww Thank you for answer. By "hanging" I mean the lack of progress - no events were published by Data Movement, all files are waiting for their timeout (and they don't generate any traffic).

If Data Movement applies those timeouts on all files individually, does it mean the timeouts can accumulate?

The sample with cancellation token could be useful if we know how long the transfer should take. In most situations it's not the case (our customers have various network conditions). Another idea could be to cancel the transfer X minutes after last received progress (of sent bytes or files). If the timeouts really accumulate, it's worth an investigation.

**Comment by blueww** [comment]
@KamilKalitaRel 

For the above CancellationTokenSource.CancelAfter(), it's for single transfer job, not for a file.
The “MaximumExecutionTime” and "ServerTimeout" in "BlobRequestOptions" is for single request, not for single file. A single file can have several requests to transfer content of it parallelly.

**Comment by KamilKalitaRel** [comment]
@blueww 
I think we can close this ticket.

We used a Delegated Handler in `HttpClient` to manipulate the timeouts throughout the transfer. It's more flexible solution than assuming a timebox for the whole transfer. We can analyze how consecutive requests react and decide, whether to continue the transfer or not (or give a feedback to the user about a bad connection).

Thank you for explaining the difference between timeout options.
