### ISSUE TITLE
Samples use deprecated nuget packages

### ISSUE THREAD

**Issue by grayjeremy** [Azure/azure-storage-net-data-movement#256]
### Which service(blob, file) does this issue concern? 
All
 
### Which version of the SDK was used?
Latest

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.Net Framework

### What problem was encountered?
    [Microsoft.Azure.Storage.Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/), the new namespace is [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs). 

This holds true for blobs, queues, and file shares
 
### Have you found a mitigation/solution?
Manually updating the dependencies, some of the class names are not the same.

**Comment by grayjeremy** [comment]
This is the same as https://github.com/Azure/azure-storage-net-data-movement/issues/242 and https://github.com/Azure/azure-storage-net-data-movement/issues/241

**Comment by amnguye** [comment]
I'm going to close this in preference for #242 since this is a duplicate.
