### ISSUE TITLE
Service copy life lock

### ISSUE THREAD

**Issue by bubyx-nektvar** [Azure/azure-storage-net-data-movement#261]
### Which service(blob, file) does this issue concern? 
Azure blob storage
 
### Which version of the SDK was used?
Nuget package Microsoft.Azure.Storage.DataMovement 2.0.1

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
.NET Core 3.1 on Windows 10

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
1. Create file of zero length in google cloud storage.
2. Create blob storage on azure
3. Run console application to transfer file from url with service copy `TransferManager.CopyAsync(sourceUrl, blobRef, true, null, context, cancellationToken) `
 
### What problem was encountered?
Application gets life locked on copy progress when i try to copy zero length file.
 
### Have you found a mitigation/solution?
Yes. I can manually check target file size, but i don't think that library should ever life lock.

**Comment by amnguye** [comment]
When you say life locked do you mean that it forever hangs on the `TransferManager.CopyAsync(sourceUrl, blobRef, true, null, context, cancellationToken)` ?

**Comment by bubyx-nektvar** [comment]
Exactly. It will hang on following:
![image](https://user-images.githubusercontent.com/17458703/112232000-231b9700-8c38-11eb-9354-0821e8b46873.png)
I created problem reproduction scenario and found out that it's probably not problem in library. But problem only occures if run application agains azure storage emulator.

So I apologize for creating this incorrect issue.
