### ISSUE TITLE
Upgrading from v2.0.1 to 2.0.2 Introduces Warnings for .NET5 Projects

### ISSUE THREAD

**Issue by Mike-E-angelo** [Azure/azure-storage-net-data-movement#267]
### Which service(blob, file) does this issue concern? 
The nuget package found here: https://www.nuget.org/packages/Microsoft.Azure.Storage.DataMovement/
 
### Which version of the SDK was used?
**2.0.2**

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
Visual Studio 2019.

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
Building a solution with version 2.0.2 in a project with a `TargetFramework` of `net5.0`.
 
### What problem was encountered?
The following warning is now emitted and did not occur in 2.0.1:

```
warning NU1701: Package 'Microsoft.Azure.Storage.DataMovement 2.0.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
```
 
### Have you found a mitigation/solution?

Not yet. :)  Wanted to post here to see if there's a nuget configuration issue inadvertently introduced on your end for 2.0.2 and/or workaround to perform.  I did a search online and did not see anything obvious.  Using 2.0.1 until then.

**Comment by amnguye** [comment]
Thanks for bringing this to our attention and apologies for the unnecessary warning that appeared. I will investigate what happened with the release. Most likely there will be another release, sorry for the inconvenience.

**Comment by amnguye** [comment]
Please kindly upgrade to 2.0.3 this should resolve the compatibility warning.

**Comment by Mike-E-angelo** [comment]
AWESOME!  Thank you so much @amnguye for the quick turn around and fix.  I was fretting that it had to do something with a bizarre configuration with my machine (using the new VS 16.10 Preview 2 which was launched a day earlier) and would require hours of obscure web searches. :P  `2.0.3` did the trick.  Thanks again!
