### ISSUE TITLE
OutOfMemoryException Copying From Azure Files to Azure Blob 

### ISSUE THREAD

**Issue by cogree** [Azure/azure-storage-net-data-movement#27]
We are copying 4.2 TB of small files from Azure File Storage to Azure Blob Storage. After a decent amount of runtime, the copy fails with an `OutOfMemoryException` coming from the await on `CopyDirectoryAsync()`. Debugging locally, we noticed that memory constantly increases indicating there may be a memory leak. I've included our relevant snippets of code below.

transfer parameters:

```
const int parallelTasks = 16;
ServicePointManager.DefaultConnectionLimit = parallelTasks;
ServicePointManager.Expect100Continue = false;
TransferManager.Configurations.ParallelOperations = parallelTasks;

var copyOptions = new CopyDirectoryOptions
{
   Recursive = true,
};
```

and the transfer code...

```
private async Task CopyDirectoryAsync(CloudFileDirectory sourceDirectory, CloudBlobDirectory destinationDirectory, CopyDirectoryOptions copyOptions,
TransferContext context)
{
   try
   {
         await TransferManager.CopyDirectoryAsync(sourceDirectory, destinationDirectory, true, copyOptions, context);
   }
   catch (TransferException)
   {

   }
   catch(Exception e)          // OutOfMemoryException wrapped in AggregateException here.
   { 
         var exceptions = new List<Exception> { e };
         var aggregateException = e as AggregateException;

         if (aggregateException != null && aggregateException.InnerExceptions != null)
            exceptions.AddRange(aggregateException.InnerExceptions);

         exceptions.ForEach(exc => this.LogException(exc, SeverityLevelEnum.Error));
         throw;
   }
}
```

**Comment by royjf** [comment]
We also run into memory error when using the CopyDirectoryAsync (v0.2.0) to perform an incremental backup from a 100+ Gigs Blob Storage to another one.

The memory usage is steady when copying new files or overwriting existing files in the destination Blob Storage. However, a significant increase in memory is observed when the Overwrite callback is used to skip files that exist in the destination Blob Storage. This may be related to the fact that explicit skip seems to trigger an Exception anyway.

Some additional information about our approach could be found here : http://markjbrown.com/azuredmlbackup/

This is, in fact, the solution we were using before running out of memory. We had to switch back to AzCopy.exe invocations using /XO /S /Y.

Interestingly, while AzCopy.exe is supposed to be based on the same API, it does not suffer from the same memory increase. Actually, files skipped by /XO are not even counted as skipped in the job summary provided by AzCopy. Is there a way to get a similar behavior with the Data movement library? This could potentially avoid the memory increase (in theory).

**Comment by peterdebruijn** [comment]
Still te case in version 0.4.1.

**Comment by EmmaZhu** [comment]
Could you check following:
1. Does your application run on 32bit or 64bit environment? 
    It could cause OOM issue with a "Prefer 32bit" application runs on 64bit environment.

2. Did you encounter any failures during transferring?  DMLib stores all failed entries in a checkpoint for later resume. If there are two many failures, there's chance to cause an OOM issue. It could mitigate the issue if you use a FileStream to persist transfer checkpoint to disk like following:
    using(FileStream journalStream = new FileStream(...)) 
    {
        DirectoryTransferContext context = new DirectoryTransferContext(journalStream);
       try 
        {
            TransferStatus status = await TransferManager.UploadDirectoryAsync(sourceDirPath, destDir, options, context, cancellationSource.Token); 
	    ...
         }
        ...
    }

**Comment by peterdebruijn** [comment]
Hi EmmaZhu,

I assue I was running the application in 32bit since I was debugging. I abandoned the library two months ago because of the errors so I would not know the answer to question 2...

**Comment by vinjiang** [comment]
It's a pity to hear that. Anyway, if you need any further assistance from us, feel free to let us know.
