### ISSUE TITLE
"1 sub transfer(s) failed." on upload

### ISSUE THREAD

**Issue by mattmcloughlin** [Azure/azure-storage-net-data-movement#28]
Hello,

The below code works fine when the network bandwidth is good - uploads complete successfully.  However, when the network is congested, the below "UploadDirectoryAsync" method throws the error "1 sub transfer(s) failed." frequently.  Are there any settings that can be modified to fix this?  Any other ideas?

```
ServicePointManager.DefaultConnectionLimit = Environment.ProcessorCount * 8;
ServicePointManager.Expect100Continue = false;
```

```
var task = TransferManager.UploadDirectoryAsync(path, directory, options, context);
task.Wait();
```

Here is the stack trace:

InnerException.StackTrace:    at Microsoft.WindowsAzure.Storage.DataMovement.MultipleObjectsTransfer.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.DataMovement.DirectoryTransfer.<ExecuteAsync>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferManager.<DoTransfer>d__2.MoveNext()

**Comment by EmmaZhu** [comment]
@mattmcloughlin 
Could you set a smaller value to `TransferManager.Configurations.ParallelOperations` to have a try? By default, DMLib transfers data with `Environment.ProcessorCount * 8` parallel operations at the same time.

**Comment by mattmcloughlin** [comment]
Hi Emma,

this wouldn't matter too much, except that the entire transfer fails if a sub-transfer fails.  How could DMLib be modified to prevent this?

thank you

**Comment by EmmaZhu** [comment]
Hi Matt,

We are planning to make a change on this behavior that it will return a transfer summary with failed transfer count instead of throwing exception. This will be included in a future release.

Thanks

**Comment by EmmaZhu** [comment]
We've already released a new DMLib which won't throw exception when there's only subtransfer fails, instead it will return a TransferStatus with summary of succeeded transfer count and failed transfer count.
Would you like to have a try?

**Comment by EmmaZhu** [comment]
We've already released a new DMLib which won't throw exception when there's only subtransfer fails, instead it will return a TransferStatus with summary of succeeded transfer count and failed transfer count.

Would you like to have a try?

**Comment by vinjiang** [comment]
Feel free to contact us if you need further assistance.
