### ISSUE TITLE
"Failed to validate destination." when using UploadDirectoryAsync

### ISSUE THREAD

**Issue by JieCarolHu** [Azure/azure-storage-net-data-movement#31]
I tried UploadAsync to upload 1 file, everything works.

But when I tried to use UploadDirectoryAsync to recursive upload a folder, I hits this "Failed to validate destination", and inner exception is "The remote server returned an error: (403) Forbidden."

CloudBlobContainer blobContainer = new CloudBlobContainer(new Uri(sasUrl));
CloudBlobDirectory destBlobDir = blobContainer.GetDirectoryReference("myDir");
UploadDirectoryOptions options = new UploadDirectoryOptions();
options.BlobType = BlobType.BlockBlob;
var task = TransferManager.UploadDirectoryAsync(sourceFolder, destBlobDir, options, context, CancellationToken.None);
task.Wait();

**Comment by EmmaZhu** [comment]
@JieCarolHu 
Sorry for any inconvenience. Currently, DMLib requests READ permission for destination in uploading to validate its existence that we'll invoke OverwriteCallback if it exists.
We are reconsidering the behavior, and you could see it in ChangeLog if we make any change in the future.

**Comment by dgodwin1175** [comment]
This seems odd to me.  So at the moment there is no way to perform an upload of an entire source directory in the same way as you can with AzCopy?

**Comment by EmmaZhu** [comment]
AzCopy also requires READ permission in destination directory. We are thinking about changing the behavior to support upgrade without READ permission.

**Comment by EmmaZhu** [comment]
AzCopy also requires READ permission in destination directory. We are thinking about changing the behavior to support uploading without READ permission.

**Comment by dgodwin1175** [comment]
I don't understand.  I have both read and write permission to the container, and using AzCopy, I can upload an entire directory.  However using TransferManager, as the original poster says, I can upload an single file using UploadAsync(), but I can't upload a directory using UploadDirectoryAsync().  I get exactly the same errors as the original poster.  Is there a fix for this yet?  Thanks.

**Comment by blueww** [comment]
DMlib support to upload with Write only SAS from 0.4 release. (Need to set ShouldOverwriteCallback as default static interface ForceOverwrite)
The same as AzCopy. (need to use /y parameter)

**Comment by EmmaZhu** [comment]
@JieCarolHu @dgodwin1175 

We've released a new DMLib (0.4.1) which should be able to address your issues. Would you like to have a try?
There's a bit interface change for new features. You can reference to samples here: https://github.com/Azure/azure-storage-net-data-movement/tree/master/samples/DataMovementSamples

Thanks
Emma
