### ISSUE TITLE
VS Project won't compile

### ISSUE THREAD

**Issue by larrywa** [Azure/azure-storage-net-data-movement#32]
When trying to build the sample project, I get the following error:

Severity    Code    Description Project File    Line    Suppression State
Error       The command "..\DMLibTestCodeGen\bin\Debug\DMLibTestCodeGen.exe bin\Debug\DMLibTest.dll Generated" exited with code -532462766. DMLibTest   C:\Users\larrywa\Downloads\DataMovement\test\DMLibTest\DMLibTest.csproj 214 

In the project DMTestLib in file DMLibTest.csproj.

Actually I can't find any .csproj files in the project at all.

**Comment by EmmaZhu** [comment]
@larrywa 
Should you share the solution file name you were building when you got the error? Is it the one under samples\DataMovementSamples or DataMovement.sln under the root folder?

**Comment by EmmaZhu** [comment]
@larrywa 
Could you share the solution file name you were building when you got the error? 
Is it the one under `samples\DataMovementSamples` or DataMovement.sln under the root folder?

**Comment by EmmaZhu** [comment]
@larrywa 
Could you share the solution file name you were building when you got the error? 
Is it the one under samples\DataMovementSamples or DataMovement.sln under the root folder?

**Comment by larrywa** [comment]
It was DataMovement.sln

**Comment by EmmaZhu** [comment]
If you only want to build sample project, you can use solution file under each sample folder. The sample codes are all put under `samples` folder. `DataMovement.sln` is used to build DataMovement library and its test codes.

**Comment by larrywa** [comment]
Ok, I see that now. Thanks!

**Comment by Yonisha** [comment]
Same issue here. Trying to build DataMovement.sln yields the same error as mentioned above:

> The command "..\DMLibTestCodeGen\bin\Debug\DMLibTestCodeGen.exe bin\Debug\DMLibTest.dll Generated" exited with code -532462766. DMLibTest C:\Users\larrywa\Downloads\DataMovement\test\DMLibTest\DMLibTest.csproj 214

In the Output window I can see more detailed error:

> Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
> 4>     at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
> 4>     at System.Reflection.RuntimeModule.GetTypes()
> 4>     at System.Reflection.Assembly.GetTypes()
> 4>     at DMLibTestCodeGen.Program.GenerateCode(String dllName, String outputFolder) in c:\Sources\azure-storage-net-data-movement\test\DMLibTestCodeGen\Program.cs:line 33
> 4>     at DMLibTestCodeGen.Program.Main(String[] args) in c:\Sources\azure-storage-net-data-movement\test\DMLibTestCodeGen\Program.cs:line 24

**Comment by EmmaZhu** [comment]
@Yonisha 
I couldn't reproduce the issue. Does it still occur? Could you try with the `Rebuild` the whole sln?

**Comment by vinjiang** [comment]
Feel free to let us know if you still hit the issue.
