### ISSUE TITLE
Inject data transform logic

### ISSUE THREAD

**Issue by blrchen** [Azure/azure-storage-net-data-movement#35]
I have some scenarios when data needs to be transformed prior to uploading to storage. One example is use my own hash algorithm to encrypt a few column data. Am thinking if DM can provide a interface where we can pass some functions for data transform and DM can call them when during the streaming process, for example, apply the function on each line or each file, etc.

**Comment by nowenL** [comment]
Same as I mentioned in #34 . How do you think about the approach to remove limitation in source stream, thus a encrypted stream can be used here for block blob & append blob.

**Comment by blrchen** [comment]
My hoping is DM sdk provides some plug in extensions so that we can do flexible transform, encrypt csv files on column level is just one example.

**Comment by blueww** [comment]
@blrchen 
Close the issue as not hear from you for a long time.
Feel free to contact us if you need any more support from us.
