### ISSUE TITLE
[Known issue] Build fail for DataMovement_k.sln in Visual studio

### ISSUE THREAD

**Issue by blueww** [Azure/azure-storage-net-data-movement#39]
repro step:
1. Sync DMlib git hub to local
2. open and build DataMovement.sln in visual studio, and it pass build
3. open and build DataMovement_k.sln in visual studio, and it fail with:

> Severity  Code    Description Project File    Line    Suppression State
> Error     An item with the same key has already been added. Key: Microsoft.WindowsAzure.Storage.DataMovement  DMLibTest   

Workaround:
1. in cmd window, cd netcore
2. run build.cmd
3. in Visual studio which has DataMovement_k.sln opened, clean solution and rebuild, then build pass

**Comment by EmmaZhu** [comment]
For in DMLibTest it needs to test multiple transferring directions(uploading/downloading/copying between append blob/block blob/page blob/azure file/file system), the test matrics are complicated, while test code should be similar. 

We have a test code generator which leverage CodeDom which is not supported with .Net Core. It cannot build the test code generator with solution DataMovement_k.sln. 

Please run build.cmd for the full build against .Net Core platform.

**Comment by blueww** [comment]
Close the issue as we should use the build script (netcore\Build.cmd) to build the solution. 
And after build with build script, build the solution in VS will also no fail.
