### ISSUE TITLE
BlockBlob Metadata not getting updated when overwriting an existing one

### ISSUE THREAD

**Issue by smkuls** [Azure/azure-storage-net-data-movement#40]
Repro - 
1. Create a CloudBlockBlob with some Metadata.
2. Get a reference to this blob.
3. Execute blob.FetchAttributes()
4. Set blob.Metadata["key"] = "value".
5. Now execute UploadAsync.

Although the blob gets overwritten however, the metadata still remains the same.

PS - The metadata does get updated in case of a blob which does not exist.

**In BlockBlobWriter.cs -** 

Based on my understanding, there is a **FetchAttributes** call, if the blob does not exist then this call fails, after that there is a call to **UploadBlobAsync** and then to **CommitAsync** which has a call to **SetAttributes** which sets the metadata.

Now, in the case when the blob already exists the **FetchAttributes** call overrides the metadata of the blob specified during **UploadBlobAsync**.

**Comment by blueww** [comment]
Thanks for reporting the issue!
DMlib 0.1-0.3 have this behavior, we have consider the issue and plan to add a interface in the future release to resolve the problem: SetAttributesCallback. The interface can be used to set blob attributes (include metadata), and DMlib will put the setting to the destination blob. 
Can it meet your requirement?

**Comment by smkuls** [comment]
Yes, I guess that should do the job.

**Comment by blueww** [comment]
The 0.4 build is released, and SetAttributesCallback() is already added to 0.4 to resolve this issue.
So close this issue as it's resolved. 
Feel free to reactive it if anything need further follow up.
