### ISSUE TITLE
ProgressTransfer class removed - code broken

### ISSUE THREAD

**Issue by cmatskas** [Azure/azure-storage-net-data-movement#44]
The ProgressTransfer class has been removed causing unit tests to fail. Could you provide some explanation on how to get hold of the progress transfer within the context of a transfer since most examples seem to refer to the old way (i.e. when ProgressTransfer was still available)
Thanks

**Comment by EmmaZhu** [comment]
The class name is changed to TransferStatus. There's already a PR to update sample code if you'd like to take a look first:
https://github.com/Azure/azure-storage-net-data-movement/pull/41

**Comment by cmatskas** [comment]
Thanks for the update! Could you explain why the examples where not changed (specifically the S3 one) to use TransferStatus instead? I haven't had the chance to run the project/tests but I think that they should be failing.
If they do, I'm happy to change it and send a PR, probably over the next few days...
Thanks again,CM

Get Outlook for iOS




On Sun, Oct 9, 2016 at 9:43 AM +0100, "Emma Zhu" <notifications@github.com> wrote:












The class name is changed to TransferStatus. There's already a PR to update sample code if you'd like to take a look first:

#41

**Comment by EmmaZhu** [comment]
We've already updated the samples in `dev` branch. Please reference to them if you'd need to.

**Comment by vinjiang** [comment]
It's also synced to master branch as well. Feel free to let us know if you have any further questions.
