### ISSUE TITLE
how to overwrite by datemodified?

### ISSUE THREAD

**Issue by EmilAlipiev** [Azure/azure-storage-net-data-movement#59]
I installed 0.4.1 version and there are some changes comparing to previous one. But I cant figure out how to overwrite my existing images if they are changed on my local directory. I believe i need to syncronize datemodified between source and destination but how can I do that?

is	ShouldOverwriteCallback  function what I am looking for? how is the usage of it?

thanks.

**Comment by hasonmsft** [comment]
@EmilAlipiev , I think you can use the ShouldTransfer for your scenario. And here is the sample code: 

```
transferContext.ShouldTransferCallback = ShouldTransferCallback;

private bool ShouldTransferCallback(object source, object dest)
{
    // source should be string for your scenario - local file
    var localPath = source as string;
    var sourceLMT = File.GetLastWriteTimeUtc(localPath);

    // Dest is blob???
    var destBlob = dest as CloudBlob;
    var destLMT = destBlob.Properties.LastModified;

    return sourceLMT > destLMT;
}
```

Hope it helps.

**Comment by prabhakarreddy1234** [comment]
I think we can achieve the same with `ShouldOverwriteCallback ` . What is the difference between `ShouldOverwriteCallback ` and `ShouldTransferCallback ` ?

**Comment by vinjiang** [comment]
@jiacfan , can you take a look?

**Comment by jiacfan** [comment]
@prabhakarreddy1234 

Sorry for late response. If you are using directory transfer, ShouldTransferCallback is recommended, it's a general should transfer callback. As design, if ShouldOverwriteCallback returns false, TransferSkippedException will be thrown to indicate that transfer actually does nothing, this is for single transfer's status reporting. If you still wish to use ShouldOverwriteCallback, please handle the exception properly.

Best Wishes,
Jiachen

**Comment by EmmaZhu** [comment]
Close this issue for now. Please feel free to reopen it or open a new one if any further assistant needed.
