### ISSUE TITLE
Cancelling UploadAsync using CancellationToken can take 3 minutes for 100MB file.

### ISSUE THREAD

**Issue by dgodwin1175** [Azure/azure-storage-net-data-movement#60]
Hi,
I'm using a CancellationToken to enable users to cancel a file upload, however for a 128MB file upload, it can take over 3 minutes for the UploadAsync exception to be raised, after the _cancellationToken.Cancel() has been called.
Note that I'm also using a TransferProgress object to track the progress of the upload, and after cancelling the upload via the token, I am still seeing my Report() method on my TransferProgress object being called multiple times before the UploadAsync exception is raised.
I've tried having a look through the DML code, but I need some help here finding out why it's taking so long.  I would have hoped that the cancellation token is checked before the progress is updated?  Can any improvements be made here?

**Comment by dgodwin1175** [comment]
Also note that the exception that is eventually thrown is a TaskCanceledException, and not an OperationCanceledException as I would expect.
Can anyone confirm the expected behaviour here?
Thanks.

**Comment by EmmaZhu** [comment]
Hi,

Could you share the version of DMLib you are using when met this issue?

TaskCanceledException is a subclass of OperationCanceledException, which should also be caught if you try to catch OperationCanceledException.

Thanks
Emma

**Comment by dgodwin1175** [comment]
Version 0.2.0.  This from my packages.config:
  <package id="Microsoft.Azure.Storage.DataMovement" version="0.2.0" targetFramework="net451" />

**Comment by EmmaZhu** [comment]
We've already have a fix in 0.4.0 for the slow cancelling issue. Would you like to have a try on the latest DataMovement library? 
We've done a slight interface change for some new feature. You can find sample codes here: https://github.com/Azure/azure-storage-net-data-movement/tree/master/samples

**Comment by dgodwin1175** [comment]
Thanks Emma.  Yes when you asked me about the version, it prompted me to update to the latest version, and the issue does appear to be resolved.
Thanks for the support.
