### ISSUE TITLE
UploadAsync Blob SAS Issue

### ISSUE THREAD

**Issue by lehne** [Azure/azure-storage-net-data-movement#61]
I am trying to use a SAS to upload via DM Library. I get a 404 and XML Exception when doing so and nothing is uploaded.
I had a similar result for #15. The SAS that I use is generated for the Blob on a server and then returned to application to be used. Which permissions do I need for the SAS in order to upload?

The exception is:
"System.Xml.XmlException":"Root element is missing."
Source: "System.Xml.ReaderWriter"
StackTrace:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)

It occurs in Executor.cs

Where it breaks at the exception, the execution state has a response: "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature."

Here is my SAS example: 
`?sv=2015-12-11&sr=b&si=some-uploads&sig=somesignature&se=2016-12-20T17:34:31Z&sp=rw&api-version=2015-12-11&timeout=300`

Here is my code:
```

var cred = new StorageCredentials(sas);

var blob = new CloudBlockBlob(uri, cred);

TransferManager.Configurations.ParallelOperations = 64;

var context = new SingleTransferContext();

context.ProgressHandler = new Progress<TransferStatus>((res) =>
{
	//progress
});

context.LogLevel = LogLevel.Verbose;

context.FileFailed += (obj, args) =>
{
  //handle failed (not called by the way)
};

await TransferManager.UploadAsync(fullFilePath, blob, null, context, token);
```

**Comment by blueww** [comment]
The Code from you works well for me with a valid Blob SAS. I don't get any failure with code on DMlib 0.4.1.

But the SAS you use looks strange (It has "sr=b" and "si", but si is for container SAS), how did you get it? Could you create a valid SAS with Azure storage client library and try again? 

If it's the problem of the Tool to create the SAS, you can open an issue for the tool which created the SAS.

**Comment by lehne** [comment]
sr=b means the resource is a blob.
si=some-uploads is referencing the policy used for upload. When creating the policy I use Write and Read permissions.

**Comment by blueww** [comment]
Hi Lehne,

How did you created the SAS? Can you use the SAS in other Azure tools?
The SAS looks not correct, such as there are no SAS parameter named "timeout", and the SAS is not URL encoded (e.g. ":" should be converted to "%3A").

You can see more details for a service SAS in https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/constructing-a-service-sas.

**Comment by blueww** [comment]
Hi Lehne,
How did you created the SAS? Can you use the SAS in other Azure tools?
The SAS is invalid, you specify permission ("sp") in both the stored access policy and the signature URI, which breaks following comments in : https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/constructing-a-service-sas 

> The access policy for a shared access signature consists of the start time, expiry time, and permissions for the signature. You can specify all of these parameters on the signature URI and none within the stored access policy; all on the container and none on the URI; or some combination of the two. However, you cannot specify a given parameter on both the signature URI and the stored access policy. See Controlling a SAS with a stored access policy for more information.
