### ISSUE TITLE
optionally disable MD5 calculation

### ISSUE THREAD

**Issue by xiongrenyi** [Azure/azure-storage-net-data-movement#64]
There's no option to disable MD5 calculation even if DisableContentMD5Validation = true can be set to disable MD5 validation.

**Comment by EmmaZhu** [comment]
Did you find the issue when uploading or downloading? Could you share more details about your scenario why you'd like to disable MD5 calculation?
The option can be used to disable MD5 calculation in downloading.  It doesn't take effect on whole file MD5 calculation in uploading.

**Comment by vinjiang** [comment]
Please let us know if you need further assistance.
