### ISSUE TITLE
Upload throughput drops when uploading larger files

### ISSUE THREAD

**Issue by rdwaite** [Azure/azure-storage-net-data-movement#65]
Hi,

I'm unsure if this is the right place to voice this. [I also have a thread open on MSDN](https://social.msdn.microsoft.com/Forums/en-US/051f42c9-e8b7-4b6f-b7e4-f2a6d92c6415/azure-data-movement-library-upload-speeds-drop-when-uploading-large-files?forum=windowsazuredata).

I'm currently using ADML (0.5.0) on a machine with 6 physical cores @ 3.5GHz and a gigabit internet connection. 

`TransferManager.UploadAsync` will upload a 1-2 GB file at an average rate of >800 Mbps; however when I try to upload a 2TB file, the average upload rate struggles to break 100 Mpbs. I have tried this on a couple other machines with similar specs with the same results. AzCopy also struggles to break the 100 Mbps upload rate with the 2TB file, but will upload smaller files close to gigabit speeds. 

All uploads are made after setting:

`ServicePointManager.DefaultConnectionLimit = Environment.ProcessorCount * 8;
ServicePointManager.Expect100Continue = false;` 

Am I neglecting to set some configuration to upload files this large? Is anyone else able to reproduce this?

**Comment by rdwaite** [comment]
Tried again today and couldn't repro.

**Comment by rdwaite** [comment]
Accidentally closed, sorry.

**Comment by rdwaite** [comment]
Other coworkers have not experienced this problem. I think it may be isolated to the machine's I've tried.

**Comment by EmmaZhu** [comment]
@rdwaite  
Did you upload the file on an Azure VM or in your own machine which is outside Azure? 
If the network is slow between your machine and Azure, could you try with a lower parallel level with TransferConfigurations.ParallelOperations? 
It may even slow down the transferring with very high parallel level in a slower network.
