### ISSUE TITLE
How do you shutdown TransferManager.

### ISSUE THREAD

**Issue by sgmoore** [Azure/azure-storage-net-data-movement#66]
I have a windows service which use TransferManager to upload a backup file (as a blob) every night.

This works fine, but when the process has complete, the CPU for the service does not return to zero and can be as high as 10%.

The problem is not as noticeable on my development machine, but attempting to profile the service still shows it spends quite a lot of time in the TransferScheduler methods StartSchedule and FillInQueue.

Is there some way I can stop all activity until the next backup?

**Comment by EmmaZhu** [comment]
TransferManager cannot be shutdown or stopped for now. We are also considering to do some change to let customers be able to shut it down. I'll update you when add this function.

**Comment by smagnetize** [comment]
Is it safe to use this library on a website?

**Comment by EmmaZhu** [comment]
@smagnetize  What kind of concern do you have? Are you worried about security or robust?

**Comment by bamo-powel** [comment]
Hey. I'm having the same problems as @sgmoore. TransferScheduler and FillInQueue are using up to 30-40% CPU on certain computers, even while idle. On other computers it's not as much of an issue (using 1-2% cpu while idle), even though it's the same methods that uses the most CPU. Shutting these down would be solving some (but not all) of the problems.

**Comment by EmmaZhu** [comment]
@bamo-powel  This is a scenario we should consider. We'll put this in our backlog.

**Comment by mms-** [comment]
May I suggest that constant 30-40% CPU usage while idle suggest something wrong with the logic/operation, not a matter of shutdown or not. Unless of course it has useful things to do while idle and not shutdown.

**Comment by neilrees** [comment]
I'm also seeing this use an excessive amount of CPU when idle, `TransferScheduler` needs to relax when it has no work to do or there needs to be some mechanism to shut it down from `TransferManager`

**Comment by EmmaZhu** [comment]
@SebastianAchatz  We've got a change from a contributor.  We are considering to take the change. The change has already passed our functional test, and we are also running Perf test against. 

Thanks
Emma

**Comment by neilrees** [comment]
@EmmaZhu Do you have any idea on when a decision might be made to release a fix?

**Comment by EmmaZhu** [comment]
@sgmoore @SebastianAchatz 
With latest version of 0.8.0 and 0.8.1, I've written a small test app to test scenario like following:
1. Upload a directory to blob with TransferManager
2. Wait

In the second phase, the CPU usage changes from 0~1%. Would you like to have a try?

**Comment by nachtneblovaK** [comment]
Hi, we have the same problem.

I have service using TransferManager for copying blobs and containers (TransferManager.CopyDirectoryAsync, TransferManager.CopyAsync). Even when nothing is trasfered for hours, it still uses about 10-15% CPU.
According to your last comment I updated library to version 0.8.1, but it doesn't help.

**Comment by mkreidenweis** [comment]
Isn't this fixed as of https://github.com/Azure/azure-storage-net-data-movement/releases/tag/v1.1.0 ?
> Fixed an issue of CPU is still in using when there's nothing being transferred in DataMovement Library


Also, the [PSH issue](https://github.com/Azure/azure-powershell/issues/4649) referring back to this issue has been marked as closed.

**Comment by blueww** [comment]
Thanks for the remind!
Close as it's fixed.
