### ISSUE TITLE
Upload sample with pause/resume

### ISSUE THREAD

**Issue by johannesegger** [Azure/azure-storage-net-data-movement#67]
We're trying to upload a large file and want to support pause/resume. However the upload doesn't finish and is stuck in the while loop:

```
TransferManager.Configurations.BlockSize = 4 * 1024 * 1024; // 4 MB

// create stream with 100 MB
var content = Enumerable
    .Range(0, 100 * 1024 * 1024)
    .Select(i => (byte)'b')
    .ToArray();
var source = new MemoryStream(content);

TransferCheckpoint checkPoint = null;
while (true)
{
    Console.Write(".");
    // Resume if there is already a checkpoint
    var context = checkPoint != null
        ? new SingleTransferContext(checkPoint)
        : new SingleTransferContext();

    context.ShouldOverwriteCallback = (src, dest) => true;
    context.LogLevel = Microsoft.WindowsAzure.Storage.LogLevel.Verbose;
    var recorder = new ProgressRecorder();
    context.ProgressHandler = recorder;
    try
    {
        // Interrupt upload after 20 seconds
        using (var cts = new CancellationTokenSource(TimeSpan.FromSeconds(20)))
        {
            await TransferManager.UploadAsync(source, blob, null, context, cts.Token);
        }
        // break if no exception occured, i.e. the upload finished
        break;
    }
    catch (OperationCanceledException) { }
    checkPoint = context.LastCheckpoint; // save the last checkpoint
}
```

What are we doing wrong?

**Comment by eggapauli** [comment]
We added some debug output after saving the checkpoint, i.e. we used the Storage API to get all uncommitted blocks and matched it with `recorder`.

We get the following output:

```
Uncommitted blocks according to Storage API
A6689033-D96E-4F9B-B238-E27891C1B1FC/custom-upload-test3: 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 = 33554432 (32 MB)
Transfer statistics according to Data Movement Library
Transferred bytes: 33554432 (32 MB); Transfered: 0; Skipped: 0, Failed: 1

Uncommitted blocks according to Storage API
A6689033-D96E-4F9B-B238-E27891C1B1FC/custom-upload-test3: 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 = 46137344 (44 MB)
Transfer statistics according to Data Movement Library
Transferred bytes: 79691776 (76 MB); Transfered: 0; Skipped: 0, Failed: 2

Uncommitted blocks according to Storage API
A6689033-D96E-4F9B-B238-E27891C1B1FC/custom-upload-test3: 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 = 46137344 (44 MB)
Transfer statistics according to Data Movement Library
Transferred bytes: 121634816 (116 MB); Transfered: 0; Skipped: 0, Failed: 3

Uncommitted blocks according to Storage API
A6689033-D96E-4F9B-B238-E27891C1B1FC/custom-upload-test3: 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 + 4194304 = 46137344 (44 MB)
Transfer statistics according to Data Movement Library
Transferred bytes: 163577856 (156 MB); Transfered: 0; Skipped: 0, Failed: 4
```

To get the list of uncommitted blocks, we used the following snippet:

```
var blockList = blob.DownloadBlockList(BlockListingFilter.Uncommitted);
var expr = string.Join(" + ", blockList.Select(b => b.Length));
var size = blockList.Sum(b => b.Length);
Console.WriteLine($"{blob.Name}: {expr} = {size} ({size/1024.0/1024.0} MB)");
```

So it almost looks like we're not capturing the context correctly, isn't it?

**Comment by hilbert-tan** [comment]
Hi @johannesegger , did you end up finding the answer? I am encountering something similar to your problem, where the resume does not actually work. It restarts the whole transfer rather than continuing halfway.

**Comment by johannesegger** [comment]
I can't remember unfortunately, but I don't think so, sry.

**Comment by dgodwin1175** [comment]
Once the upload is cancelled, you can save the checkpoint like this:

            try
            {
                return TransferManager.UploadAsync(file.FileName, destinationBlob, options, context, token);
            }
            catch (TaskCanceledException ex)
            {
                checkpoint = context.LastCheckpoint;
                memoryStream = new MemoryStream();
                formatter.Serialize(memoryStream, checkpoint);
                file.Checkpoint = Convert.ToBase64String(memoryStream.ToArray());
                throw ex;
            }

And to resume your upload from the saved checkpoint:

            memoryStream = new MemoryStream(Convert.FromBase64String(file.Checkpoint));
            checkpoint = formatter.Deserialize(memoryStream) as TransferCheckpoint;
            var context = new SingleTransferContext(checkpoint);
            context.SetAttributesCallback = (destination) =>
            {
                var destBlob = destination as CloudBlob;
                destBlob.Properties.ContentType = ContentType;
            };

Then upload the file again with the above context object.

**Comment by vinjiang** [comment]
@blueww , can you take a look?

**Comment by blueww** [comment]
@johannesegger 
DMlib don't support resume when transfer is upload from stream , or download to stream. It only support resume upload/download when it's from/to a File.
If you use latest DMlib 0.7.1, you will see following exception when try to resume from stream, and it indicate resume from stream is not supported:

```
Microsoft.WindowsAzure.Storage.DataMovement.TransferException: Resuming transfer from or to a stream is not supported. 
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferManager.GetTransfer(TransferLocation sourceLocation, TransferLocation destLocation, TransferMethod transferMethod, TransferContext transferContext) in C:\Local\Jenkins\jobs\DMLib_0.7.1\workspace\lib\TransferManager.cs:line 1329
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferManager.GetOrCreateSingleObjectTransfer(TransferLocation sourceLocation, TransferLocation destLocation, TransferMethod transferMethod, TransferContext transferContext) in C:\Local\Jenkins\jobs\DMLib_0.7.1\workspace\lib\TransferManager.cs:line 1275
   at Microsoft.WindowsAzure.Storage.DataMovement.TransferManager.UploadAsync(Stream sourceStream, CloudBlob destBlob, UploadOptions options, SingleTransferContext context, CancellationToken cancellationToken) in C:\Local\Jenkins\jobs\DMLib_0.7.1\workspace\lib\TransferManager.cs:line 155
   at ConsoleApp1.Program.Main(String[] args) in c:\users\weiwei\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 48
```

**Comment by johannesegger** [comment]
That exception is very very helpful, thanks a lot.

However what's the problem with supporting resume from a stream? It should be possible if [`stream.CanSeek`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=netstandard-2.0) returns `true`, right?

**Comment by blueww** [comment]
In DMlib 0.7.1, we support none-seekable stream, so currently resume will not be supported on all stream, even it's seekable.

**Comment by johannesegger** [comment]
Ok, thanks. I'm glad I can finally close this issue :-)

**Comment by thomaslevesque** [comment]
> I have opened a task to track the feature request of supporting resume on seekable stream.

Hi @blueww, I can find the issue you mentioned. Can you link to it?

**Comment by blueww** [comment]
@johannesegger 
The task is a internal dev work track item for the DMlib. We will use the task to track all the dev work of DMlib.
So you might don't have access to it. Following is the link. 
https://msazure.visualstudio.com/One/XStore-XClient/_workitems/edit/2997553

**Comment by johannesegger** [comment]
@thomaslevesque the above is for you

**Comment by thomaslevesque** [comment]
Ah, but it's not public, so the link is useless to me... @blueww any idea when this will be implemented?

**Comment by blueww** [comment]
We will priority this according to our bandwidth and other feature requests.

**Comment by haldarsumana** [comment]
Is there a way to save context.LastCheckpoint in the database or as a file to use it later to start blob upload from the last checkpoint by using Azure Data Movement library?
