### ISSUE TITLE
SearchPattern to exclude files with specific extension

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Azure/azure-storage-net-data-movement#77]
Is there a way i can specify `SearchPattern` in `DirectoryOptions` to exclude all the blobs with `.png` extension while copying across multiple Blob containers ?

**Comment by EmmaZhu** [comment]
The pattern doesn't support this. There is a filter callback `ShouldTransferCallback` in `DirectoryTransferContext`. You can implement your own transfer filter with it.

**Comment by EmmaZhu** [comment]
The pattern doesn't support this. There is a filter callback ShouldTransferCallback in DirectoryTransferContext. You can implement your own transfer filter with it.

**Comment by prabhakarreddy1234** [comment]
Thanks. That's exactly what i did and it worked.

**Comment by JagDTalcyon** [comment]
Thanks for the question. Can you please send me the code snippet for this.
