### ISSUE TITLE
How to know which data slice is being copied

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Azure/azure-storage-net-data-movement#80]
I have  40 mil blobs of  10 TB in blob storage. I am using DML to copy these into another storage account for backup purpose. It took nearly 2 weeks to complete. Now i am worried that until which date the blobs are copied to target directory. Is it the date when the job started or the date job finished ?

Does DML uses anything like data slices ?

**Comment by EmmaZhu** [comment]
Are you invoking `CopyDirectoryAsync` to copy blobs? Did you assign `true` or `false` to `isServiceCopy` when invoking the method? Are the two storage account in the same DC or not?
You can use `ProgressHandler` in `TransferContext` to monitor copying progress.

**Comment by prabhakarreddy1234** [comment]
Yes. I am invoking `CopyDirectoryAsync`.
Yes. I assigned `IsServiceCopy = True`
They are not in the same DC as it is backup, i want to make sure the backup lives in other DC.
I am using ProgressHandler and it is showing the copy progress. But not sure which file is transferred. I mean, the file uploaded after the copy process started ?

**Comment by EmmaZhu** [comment]
There is an EventHandler `FileTransferred` in `DirectoryTransferContext` which can be used to monitor files got copied successfully, the EventHandler `FileFailed` can be used to monitor transfer failures.

**Comment by prabhakarreddy1234** [comment]
I am using `FileTransferred`, `FilesSkipped`, `FileFailed` call backs. But my question is about the dataslice which is being copied.  If during the copy, if i add another blob to the blob storage then would that new blob as well be copied to the destination ?  
If yes, When does the job gets completed in the case where high volume applications pushing blobs into blob storage continuously 24/7 ? 
If No,  What should be the dataslice start and end times ? can we configure it ?

**Comment by blueww** [comment]
DMLib don't support changing source and destination. 

From the code perspective, if the new added blob name location in the list sequence is still not listed by DMlib (such as you add a blob with name "z", and DMlib just list to "a"), it will be transferred by DMlib finally; else (e.g. you add blob name "a", and DMlib list to "z"), then the blob will not be transferred.

**Comment by vinjiang** [comment]
@EmmaZhu , please follow up the remaining questions.

**Comment by EmmaZhu** [comment]
@prabhakarreddy1234  
Have our reply answered your questions? Do you need our further assistant?

**Comment by EmmaZhu** [comment]
Close this issue for now. Please feel free to reopen it or open a new one if any further assistant needed.
