### ISSUE TITLE
"Upload file in root directory with stream" doesn't work, has wrong API

### ISSUE THREAD

**Issue by andrewb-ms** [Azure/azure-storage-net-data-movement#95]
The "Upload file in root directory with stream" command shows this error when I use it:

Message               : Could not find a transformer to transform "SimpleDataType{type=org.glassfish.grizzly.utils.BufferInputStream, mimeType='*/*', encoding='null'}" to "SimpleDataType{type=org.mule.modules.azurestorageservice.inputentity.RootFileUploadByStream, mimeType='*/*', encoding='null'}"

I am trying to pass the output of an HTTP Request that downloads a file into the Azure Storage Connector to then upload this data to Azure. 

However, when I try to do that I get the above error.  This connect needs to take the upload path as a parameter that can be set not via the payload.  Moreover, this connector should not require specialized types as the payload - it should be able to take any input stream.

**Comment by andrewb-ms** [comment]
PS- Here is the input I used as "File Reference":

#[payload]

**Comment by EmmaZhu** [comment]
@andrewb-ms 
Did you meet this error when using DMLib or other tools? If you are using DMLib, could you share the code?

**Comment by vinjiang** [comment]
Feel free to let us know if you need further assistance.
