### ISSUE TITLE
High Memory Consumption

### ISSUE THREAD

**Issue by KiranBabu-Kirando** [Azure/azure-storage-net-data-movement#96]
We are currently testing with 1 MB files for the past few days. Our app does around 1 million downloads per hour and now we see lot of memory consumption. Our machine has 16 GB RAM and around 90% of memory is consumed. Does DML code leak memory ?

int threadsToUse = 300;
ThreadPool.SetMinThreads(threadsToUse, threadsToUse / 2);
            
ServicePointManager.DefaultConnectionLimit = 1000;
ServicePointManager.Expect100Continue = false;
TransferManager.Configurations.ParallelOperations = threadsToUse;

**Comment by EmmaZhu** [comment]
@KiranBabu-Kirando  
DMLib has a limited sized cache which should not take so much memory. 

Does DMLib succeed in all of these downloading? Is there any failure? Could you share the version of DMLib you are using? If it's OK, could you also share the code of how you are invoking DMLib?

**Comment by KiranBabu-Kirando** [comment]
@EmmaZhu 
Ignore my initial query on 1 MB. I found out the problem and fixed. Disposing the cancellation token source solved that issue. 

**1. I am downloading a mix of blobs whose sizes are from a few bytes to 2 GB. I see the memory is fluctuating between 1 GB and 3 GB. Looking at the dump shows high memory consumption is in MemoryManager Byte Array that has 4MB in each cell. Is this expected ? 
2. Have you guys done any load testing and could you share those results ?**


NOTE: Since we need SHA256 hash validation we have customized DML code to our needs. We copied the StreamWriter class and added SHA256 hash validation.


            long transferStartTick = 0, transferEndTick = 0, startTick = 0, endTick = 0;

            NetNativeMethods.QueryPerformanceCounter(ref transferStartTick);

            Task progressMonitorTask = null;
            Task downloadTask = null;

            RetryStrategy retryStrategy = new Incremental("IncrementalStrategy",
                                            _fileTransferConfiguration.IncrementalRetryCount,
                                            _fileTransferConfiguration.IncrementalRetryInterval,
                                            _fileTransferConfiguration.IncrementalRetryIntervalIncrement, true);

            RetryStrategy exponentialRetryStrategy = new ExponentialBackoff("ExponentialRetry",
                _fileTransferConfiguration.ExponentialRetryCount,
                _fileTransferConfiguration.ExponentialRetryMinBackOff,
                _fileTransferConfiguration.ExponentialRetryMaxBackOff,
                _fileTransferConfiguration.ExponentialRetryDeltaBackOff, true);

            FileTransientErrorDetectionStrategy fileTransientErrorDetectionStrategy = new FileTransientErrorDetectionStrategy(requestId, sourceUri.Uri, destinationUri.Uri, TransferAction.TransferFile);
            RetryPolicy blobRetryPolicy = new RetryPolicy(fileTransientErrorDetectionStrategy, retryStrategy);
            blobRetryPolicy.Retrying += RetryPolicy_Retrying;

            FileTransientErrorDetectionStrategy fileTransientCreateDirErrorDetectionStrategy = new FileTransientErrorDetectionStrategy(requestId, sourceUri.Uri, destinationUri.Uri, TransferAction.CreateDirectory);
            RetryPolicy createDirRetryPolicy = new RetryPolicy(fileTransientCreateDirErrorDetectionStrategy, exponentialRetryStrategy);
            createDirRetryPolicy.Retrying += ExponentialRetryPolicy_Retrying;

            var fileTransferCompleted = new FileTransferCompleted();

            var localCancellationTokenSource = new CancellationTokenSource();
            var localCancellationToken = localCancellationTokenSource.Token;

            var linkedCancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(localCancellationToken, externalCancellationToken);
            var linkedCancellationToken = linkedCancellationTokenSource.Token;

            try
            {
                SingleTransferContext sharedTransferContext = new SingleTransferContext();
                sharedTransferContext.ClientRequestId = requestId.ToString();
                
                sharedTransferContext.ShouldOverwriteCallback = (source, destination) =>
                {
                    return true;
                };

                NetNativeMethods.QueryPerformanceCounter(ref startTick);
                var sourceBlob = new CloudBlockBlob(new Uri(sourceUri.Uri));
                sourceBlob.FetchAttributes();
                var sourceFileSize = sourceBlob.Properties.Length;

                string targetFilePath = Path.Combine(destinationUri.Uri, sourceBlob.Name);

                _fileHelper.CreateDirectory(Path.GetDirectoryName(targetFilePath), createDirRetryPolicy);
                NetNativeMethods.QueryPerformanceCounter(ref endTick);

                fileTransferCompleted.FileTransferPreProcessingTimeMs = ((endTick - startTick) * 1000) / Stopwatch.Frequency;

                ProgressRecorder recorder = new ProgressRecorder(requestId, sourceUri.Uri, targetFilePath, sourceFileSize, TransferStrategyType.DmlBlobDownloadTransferStrategy, _fileTransferConfiguration.ProgressUpdateInterval, progress);
                sharedTransferContext.ProgressHandler = recorder;

                DownloadOptions options = new DownloadOptions();
                options.DisableContentMD5Validation = false;
                options.Hash = sourceUri.HashInfo != null ? new HashInfo() { Hash = sourceUri.HashInfo.Hash, CryptoServiceProvider = sourceUri.HashInfo.CryptoServiceProvider } : null;
                options.LogChunkProgress = false;

                progressMonitorTask = ProgressMonitorTask(requestId, sourceUri.Uri, targetFilePath, sourceFileSize, recorder, localCancellationTokenSource, linkedCancellationToken, externalCancellationToken);

                downloadTask = Task.Run(async () =>
                {
                    try
                    {
                        NetNativeMethods.QueryPerformanceCounter(ref startTick);
                        await _fileTransferHelper.DMLDownloadBlob(sourceBlob, targetFilePath, options, sharedTransferContext, linkedCancellationToken).ConfigureAwait(false);
                        NetNativeMethods.QueryPerformanceCounter(ref endTick);
                        fileTransferCompleted.FileTransferTimeMs = ((endTick - startTick) * 1000) / Stopwatch.Frequency;

                        NetNativeMethods.QueryPerformanceCounter(ref startTick);
                        _fileHelper.SetFileAttribute(targetFilePath);
                        NetNativeMethods.QueryPerformanceCounter(ref endTick);
                        fileTransferCompleted.FileTransferPostProcessingTimeMs = ((endTick - startTick) * 1000) / Stopwatch.Frequency;

                        NetNativeMethods.QueryPerformanceCounter(ref transferEndTick);
                        fileTransferCompleted.TotalTransferTimeMs = ((transferEndTick - transferStartTick) * 1000) / Stopwatch.Frequency;

                        fileTransferCompleted.EndTime = DateTimeOffset.UtcNow;
                        fileTransferCompleted.RequestId = requestId;
                        fileTransferCompleted.SourceUri = sourceUri.Uri;
                        fileTransferCompleted.SourceLocationType = sourceUri.DataLocationType;
                        fileTransferCompleted.DestinationUri = targetFilePath;
                        fileTransferCompleted.DestinationLocationType = destinationUri.DataLocationType;
                        fileTransferCompleted.IsNetworkShare = new Uri(destinationUri.Uri).IsUnc;
                        fileTransferCompleted.SizeinBytes = sourceFileSize;
                        fileTransferCompleted.TransferStrategyType = TransferStrategyType.DmlBlobDownloadTransferStrategy;
                        fileTransferCompleted.LogInformational();
                    }
                    catch (Exception ex)
                    {
                        if (externalCancellationToken.IsCancellationRequested)
                        {
                            throw;
                        }
                        else if (localCancellationToken.IsCancellationRequested)
                        {
                            //do nothing
                        }
                        else
                            throw;
                    }
                    finally
                    {
                        localCancellationTokenSource.Cancel();
                    }
                });

                Task[] tasks = new Task[] { downloadTask, progressMonitorTask };
                await Task.WhenAll(tasks).ConfigureAwait(false);

                //Location of downloaded file path with file name
                destinationUri.Uri = targetFilePath;
                destinationUri.HashInfo = options.Hash;
                destinationUri.SizeInBytes = sourceFileSize;
            }
            catch (OperationCanceledException exp)
            {
                if (externalCancellationToken.IsCancellationRequested)
                {
                    throw;
                }
                else if (localCancellationToken.IsCancellationRequested)
                {
                    //do nothing.
                }
                else if (downloadTask != null && downloadTask.IsFaulted)
                {
                    throw downloadTask.Exception;
                }
                else if (progressMonitorTask != null && progressMonitorTask.IsFaulted)
                {
                    throw progressMonitorTask.Exception;
                }
                else
                    throw;
            }
            catch (TransferException exp)
            {
                if (exp?.InnerException is StorageException)
                {
                    var exp1 = ((StorageException)exp.InnerException);

                    if (exp1?.RequestInformation?.HttpStatusCode == 403)
                        throw new ForbiddenAccessException($"unable to access blob Uri {sourceUri.Uri} due to: {exp.Message}, it may be blob SAS Uri is expired, please check the verify expiry and permission settings of Uri");

                    if (exp1?.RequestInformation?.HttpStatusCode == 404)
                        throw new BlobDoesNotExistsException($"unable to access blob Uri {sourceUri.Uri} due to: {exp.Message}, please check the uri and see if actually exists!");

                    if (exp1?.RequestInformation?.ExtendedErrorInformation?.ErrorCode == StorageErrorCodeStrings.AuthenticationFailed)
                    {
                        throw new AzureStorageAuthenticationFailedException(exp.Message,
                            exp1.RequestInformation.ExtendedErrorInformation.ErrorCode, exp.InnerException);
                    }
                }

                throw;
            }
            catch (ArgumentException exp)
            {
                if (exp.ParamName.Equals("blobaddress", StringComparison.InvariantCultureIgnoreCase)
                    && exp.Source.Equals("Microsoft.WindowsAzure.Storage", StringComparison.InvariantCultureIgnoreCase))
                {
                    throw new FileNotAvailableException($"Unable to access blob Uri {sourceUri.Uri} due to {exp.Message}");
                }
                throw;
            }
            catch (InvalidOperationException exp)
            {
                if (exp?.InnerException is HashValidationFailedException)
                    throw exp.InnerException;

                if (exp?.InnerException is BlobDoesNotExistsException)
                    throw new BlobDoesNotExistsException($"unable to access blob Uri {sourceUri.Uri} due to: {exp.Message}, please check the uri and see if actually exists!");

                throw;
            }
            catch (DMLTransferNoProgressReportedException npexp)
            {
                throw npexp;
            }
            catch (StorageException exp)
            {
                if (((StorageException)exp)?.RequestInformation?.HttpStatusCode == 403)
                    throw new ForbiddenAccessException($"unable to access blob Uri {sourceUri.Uri} due to: {exp.Message}, it may be blob SAS Uri is expired, please check the verify expiry and permission settings of Uri");

                if (((StorageException)exp)?.RequestInformation?.HttpStatusCode == 404)
                    throw new BlobDoesNotExistsException($"unable to access blob Uri {sourceUri.Uri} due to: {exp.Message}, please check the uri and see if actually exists!");

                throw;
            }
            catch (Exception exp)
            {
                throw;
            }
            finally
            {
                blobRetryPolicy.Retrying -= RetryPolicy_Retrying;
                createDirRetryPolicy.Retrying -= ExponentialRetryPolicy_Retrying;

                //cancel the progress monitor task.
                if (!localCancellationTokenSource.IsCancellationRequested)
                    localCancellationTokenSource.Cancel();

                if (linkedCancellationTokenSource != null)
                {
                    linkedCancellationTokenSource.Dispose();
                    linkedCancellationTokenSource = null;
                }

                if (localCancellationTokenSource != null)
                {
                    localCancellationTokenSource.Dispose();
                    localCancellationTokenSource = null;
                }
            }

**Comment by KiranBabu-Kirando** [comment]
@EmmaZhu,
Do you have any load testing data that I could use. When we look at our dump we see lot of memory allocated to the MemoryCell object. 
What is the max memory that we can expect to use ?
Is there anything else that we need to do to fix this issue ?

**Comment by EmmaZhu** [comment]
@KiranBabu-Kirando  The MemoryManager is a cache for chunks during uploading/downloading, MemoryManager maximum size is BlockSize * Parallel Level * 3, which is 4MB * core * 8 * 3 by default, which is 768MB on an 8 cores machine. During transferring, it will keeps at the a size and won't release the memory it has allocated until process exits. If your memory keeps change from 1GB to 3GB, there is might be some other objects reserving memory. 
To transfer a container/directory with a large number of blobs/files, if there's many failures during transfer, the transfer instance in checkpoint could take a lot memory.

Which version of DMLib you integrated to? The latest DMLib supports to write checkpoint to a stream (you can use a file stream to save checkpoint to disk), which would take less memory when there's many failures.

**Comment by vinjiang** [comment]
Feel free to let us know if you need further assistance.
